-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(a99b7aee)", "rgba(1B1B1Bee)", "rgba(1B1B1Bee)", "rgba(a99b7aee)" },
        angle = 5,
      },
      inactive_border = "rgb(1B1B1B)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
    col = {
      border_active = {
        colors = { "rgba(e75a50ee)", "rgba(1B1B1Bee)", "rgba(1B1B1Bee)", "rgba(e75a50ee)" },
        angle = 5,
      },
      border_inactive = "rgb(1B1B1B)",
    },
    groupbar = {
      col = {
        active = "rgba(e75a5088)",
        inactive = "rgba(1B1B1Baa)",
      },
      text_color = "rgb(efebdc)",
      text_color_inactive = "rgba(a99b7aaa)",
    },
  },
  decoration = {
    rounding = 3,
    rounding_power = 3,
    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(00000052)",
    },
    blur = {
      enabled = true,
      size = 2,
      passes = 2,
      special = true,
      brightness = 0.40,
      contrast = 0.75,
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
