mode = "dark"

# Accent
accent = "#9ECE6A"

# Selection / Muted
selection = "#2F3B25"
muted = "#414868"

# Backgrounds
background = "#1A1B26"
dark_background = "#13141C"
darker_background = "#0E0E14"
lighter_background = "#24283B"

# Foregrounds
foreground = "#A9B1D6"
dark_foreground = "#565F89"
light_foreground = "#B4BEE6"
bright_foreground = "#C0CAF5"

# Colors
red = "#F7768E"
yellow = "#E0AF68"
orange = "#EB927B"
green = "#9ECE6A"
cyan = "#449DAB"
blue = "#7AA2F7"
magenta = "#AD8EE6"
brown = "#75493D"

# Bright colors
bright_red = "#FF7A93"
bright_yellow = "#FF9E64"
bright_green = "#B9F27C"
bright_cyan = "#0DB9D7"
bright_blue = "#7DA6FF"
bright_magenta = "#BB9AF7"
