package runtime

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestShellAdapterSkipsMissingAndBarOnlyShellConfig(t *testing.T) {
	adapter, err := NewShellAdapter()
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		name string
		data string
	}{
		{name: "missing"},
		{name: "bar-only", data: "# Generated by Omagen.\n[bar]\nbackground-alpha = 0.82\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			themeRoot := t.TempDir()
			if tc.data != "" {
				if err := os.WriteFile(filepath.Join(themeRoot, shellConfigFile), []byte(tc.data), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			request := testActivationRequest("shell")
			request.ThemeRoot = themeRoot
			if err := adapter.Preflight(context.Background(), request); err != nil {
				t.Fatal(err)
			}
			result, err := adapter.Activate(context.Background(), request)
			if err != nil {
				t.Fatal(err)
			}
			if result.State != FeatureSkipped {
				t.Fatalf("bar-only or missing Shell input should skip: %#v", result)
			}
		})
	}
}

func TestShellAdapterReportsNativeShellTokensReady(t *testing.T) {
	themeRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(themeRoot, shellConfigFile), []byte("# Generated by Omagen.\n[popups]\nbackground-alpha = 0.82\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	adapter, err := NewShellAdapter()
	if err != nil {
		t.Fatal(err)
	}
	request := testActivationRequest("shell")
	request.ThemeRoot = themeRoot
	result, err := adapter.Activate(context.Background(), request)
	if err != nil {
		t.Fatal(err)
	}
	if result.State != FeatureReady || result.Owner != OwnerQuickshell || result.Feature != FeatureShell {
		t.Fatalf("unexpected Shell activation result: %#v", result)
	}
}

func TestShellAdapterDeactivationOwnsNoPersistentState(t *testing.T) {
	adapter, err := NewShellAdapter()
	if err != nil {
		t.Fatal(err)
	}
	result, err := adapter.Deactivate(context.Background(), DeactivationRequest{ThemeName: "generated-theme", Reason: "test"})
	if err != nil {
		t.Fatal(err)
	}
	if result.State != FeatureInactive || len(result.OwnedPaths) != 0 {
		t.Fatalf("Shell deactivation should not claim persistent files: %#v", result)
	}
}
