background            #181a1f
foreground            #b9bec6
selection_background  #2b2f37
selection_foreground  #eceff2

background_opacity 0.90

# black
color0  #181a1f
color8  #4b515b

# red
color1  #e53939
color9  #ff5c5c

# green
color2  #dce0e6
color10 #eceff2

# yellow
color3  #9e1a1a
color11 #f04a4a

# blue
color4  #ad2222
color12 #dce0e6

# magenta
color5  #c3c8d0
color13 #f5f7f9

#cyan
color6  #8f949c
color14 #aab0b9

#white
color7  #b9bec6
color15 #eceff2
