-- Generated by hypr2lua-web.
-- Source: hyprland.conf

local activeBorderColor = {
  colors = { "rgba(82eeffee)", "rgba(82eeffee)", "rgba(b388ebee)", "rgba(b388ebee)", "rgba(b388ebee)", "rgba(b388ebee)" },
  angle = 90,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = "rgb(3d4455)",
    },
    gaps_in = 6,
    gaps_out = 8,
    border_size = 1,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = "rgb(3d4455)",
    },
    groupbar = {
      col = {
        active = "rgba(4ecdc4ff)",
        inactive = "rgba(3d4455ff)",
      },
      text_color = "rgba(181c22ff)",
    },
  },
  decoration = {
    rounding = 6,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(0a0c12ee)",
      color_inactive = "rgba(0a0c12ee)",
    },
    blur = {
      enabled = false,
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("expressiveFastSpatial", { type = "bezier", points = { { 0.42, 1.67 }, { 0.21, 0.90 } } })
hl.curve("expressiveSlowSpatial", { type = "bezier", points = { { 0.39, 1.29 }, { 0.35, 0.98 } } })
hl.curve("expressiveDefaultSpatial", { type = "bezier", points = { { 0.38, 1.21 }, { 0.22, 1.00 } } })
hl.curve("emphasizedDecel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("emphasizedAccel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("standardDecel", { type = "bezier", points = { { 0, 0 }, { 0, 1 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.52, 0.03 }, { 0.72, 0.08 } } })

hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "popin 80%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "emphasizedDecel",
  style = "popin 90%",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "slide",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 10,
  bezier = "emphasizedDecel",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 2.7,
  bezier = "emphasizedDecel",
  style = "popin 93%",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 2.4,
  bezier = "menu_accel",
  style = "popin 94%",
})
hl.animation({
  leaf = "fadeLayersIn",
  enabled = true,
  speed = 0.5,
  bezier = "menu_decel",
})
hl.animation({
  leaf = "fadeLayersOut",
  enabled = true,
  speed = 2.7,
  bezier = "menu_accel",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 7,
  bezier = "menu_decel",
  style = "slide",
})
hl.animation({
  leaf = "specialWorkspaceIn",
  enabled = true,
  speed = 2.8,
  bezier = "emphasizedDecel",
  style = "slidevert",
})
hl.animation({
  leaf = "specialWorkspaceOut",
  enabled = true,
  speed = 1.2,
  bezier = "emphasizedAccel",
  style = "slidevert",
})

hl.window_rule({
  opacity = "1.0 override 1.0 override",
  no_dim = true,
  match = {
    class = ".*",
  },
})
