background = #0d0506
foreground = #ffc8c6
cursor-color = #fff6f6
selection-background = #45111b
selection-foreground = #fff6f6

palette = 0=#0d0506
palette = 1=#c64b5c
palette = 2=#c84a5c
palette = 3=#c44d5d
palette = 4=#c9475a
palette = 5=#c34f5e
palette = 6=#c54d5d
palette = 7=#ffc8c6
palette = 8=#715555
palette = 9=#ee5f72
palette = 10=#ec6173
palette = 11=#f05d71
palette = 12=#ed6173
palette = 13=#f15b70
palette = 14=#f05e72
palette = 15=#fff6f6
