-- Generated by Omagen. Window style: border=neon border_size=4 shape=rounded spacing=native depth=shadow active=native inactive=shadow_only.
local active_border_color = { colors = { "rgb(de555d)", "rgb(c34f5e)" }, angle = 0 }
local inactive_border_color = "rgb(9d6b6b)"
if _omagen_border_angle_timer then _omagen_border_angle_timer:set_enabled(false) end
if _omagen_glitch_timer then _omagen_glitch_timer:set_enabled(false) end
if _omagen_glitch_cleanup then _omagen_glitch_cleanup() end
if _omagen_window_opacity_cleanup then _omagen_window_opacity_cleanup() end
if _omagen_window_opacity_rule then _omagen_window_opacity_rule:set_enabled(false) end
_omagen_glitch_burst = function() end
_omagen_window_opacity_handshake = function() end
local active_shadow_color = "rgba(de555dd0)"
local inactive_shadow_color = "rgba(9d6b6b55)"
local active_glow_color = "rgba(de555dd0)"
local inactive_glow_color = "rgba(9d6b6b35)"

hl.config({
  general = {
    col = { active_border = active_border_color, inactive_border = inactive_border_color },
    border_size = 4,
  },
  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },
  decoration = {
    rounding = 8, rounding_power = 3,
    active_opacity = 1.00,
    inactive_opacity = 1.00,
    shadow = { enabled = true, render_power = 3, range = 24, color = active_shadow_color, color_inactive = inactive_shadow_color },
    glow = { enabled = true, range = 16, render_power = 3, color = active_glow_color, color_inactive = inactive_glow_color },
  },
})

-- Blur translucent native Quickshell surfaces for the Shell Glass preset.
hl.layer_rule({ name = "omagen-shell-glass-backdrop-blur", match = { namespace = "^((omarchy-(bar|menu|image-selector|emojis|clipboard|keyboard-panel|notifications|osd|polkit|lock-preview|network-qr|reminders))|omagen-shell-demo|omagen-live-canvas)$" }, blur = true, blur_popups = true, ignore_alpha = 0.20 })
hl.curve("omagenDigital", { type = "bezier", points = { { 0.05, 0.92 }, { 0.12, 1 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "omagenDigital" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "omagenDigital", style = "gnomed" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.1, bezier = "omagenDigital", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = false })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 0.5, bezier = "omagenDigital" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 1.6, bezier = "omagenDigital" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "omagenDigital", style = "slide 12%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 1.8, bezier = "omagenDigital", style = "slidevert" })
hl.animation({ leaf = "border", enabled = true, speed = 0.7, bezier = "omagenDigital" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 0.7, bezier = "omagenDigital" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 0.7, bezier = "omagenDigital" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 0.7, bezier = "omagenDigital" })
hl.animation({ leaf = "layers", enabled = true, speed = 1.8, bezier = "omagenDigital" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 1.8, bezier = "omagenDigital", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 0.9, bezier = "omagenDigital", style = "slide" })

-- Per-window materialization: scoped entrance opacity, then restore user ownership.
_omagen_window_opacity_pending = _omagen_window_opacity_pending or {}
_omagen_window_opacity_rule = hl.window_rule({
  name = "omagen-window-materialization",
  match = { tag = "omagen-materializing" },
  opacity = "0.82 override 0.82 override 0.82 override",
})
local _omagen_window_opacity_release = function(selector)
  hl.dispatch(hl.dsp.window.tag({ tag = "-omagen-materializing", window = selector }))
end

_omagen_window_opacity_cleanup = function()
  for selector, timer in pairs(_omagen_window_opacity_pending) do
    if timer then timer:set_enabled(false) end
    _omagen_window_opacity_release(selector)
  end
  _omagen_window_opacity_pending = {}
end

_omagen_window_opacity_handshake = function(window)
  if not window or not window.address then return end
  local selector = "address:" .. tostring(window.address)
  if _omagen_window_opacity_pending[selector] then return end
  hl.dispatch(hl.dsp.window.tag({ tag = "+omagen-materializing", window = selector }))
  local timer
  timer = hl.timer(function()
    timer:set_enabled(false)
    _omagen_window_opacity_release(selector)
    _omagen_window_opacity_pending[selector] = nil
  end, { timeout = 110, type = "repeat" })
  _omagen_window_opacity_pending[selector] = timer
end
hl.on("window.open", function(window) _omagen_window_opacity_handshake(window) end)

-- Cyberpunk signal: event-triggered whole-desktop glitch, idle-off.
local _omagen_glitch_flash_border = { colors = { "rgb(c34f5e)", "rgb(c9475a)", "rgb(de555d)" }, angle = 90 }
local _omagen_glitch_shader = (os.getenv("HOME") or "") .. "/.local/state/omarchy/current/theme/omagen-cyberpunk-glitch.frag"
local _omagen_glitch_configured_shader = select(1, hl.get_config("decoration.screen_shader"))
local _omagen_glitch_base_screen_shader = _omagen_glitch_configured_shader
if type(_omagen_glitch_base_screen_shader) ~= "string" then _omagen_glitch_base_screen_shader = "" end
local _omagen_glitch_configured_damage_tracking = select(1, hl.get_config("debug.damage_tracking"))
local _omagen_glitch_base_damage_tracking = tonumber(_omagen_glitch_configured_damage_tracking) or 2
_omagen_glitch_owned = false

-- The shader's time uniform needs full damage tracking while it is active.
_omagen_glitch_cleanup = function()
  if _omagen_glitch_timer then _omagen_glitch_timer:set_enabled(false) end
  if _omagen_glitch_owned then
    hl.animation({ leaf = "borderangle", enabled = false })
    hl.config({
      general = { col = { active_border = active_border_color } },
      group = { col = { border_active = active_border_color } },
      decoration = { screen_shader = _omagen_glitch_base_screen_shader },
      debug = { damage_tracking = _omagen_glitch_base_damage_tracking },
    })
    _omagen_glitch_owned = false
  end
end

_omagen_glitch_burst = function()
  if _omagen_glitch_owned then
    -- Window creation can immediately produce related workspace, panel, or
    -- notification signals. Coalesce them into the active pulse instead of
    -- repeatedly restarting its strongest attack and trapping the display in
    -- continuous distortion.
    return
  end
  hl.config({
    general = { col = { active_border = _omagen_glitch_flash_border } },
    group = { col = { border_active = _omagen_glitch_flash_border } },
    decoration = { screen_shader = _omagen_glitch_shader },
    debug = { damage_tracking = 0 },
  })
  hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "linear", style = "loop" })
  _omagen_glitch_owned = true
  if _omagen_glitch_timer then _omagen_glitch_timer:set_enabled(true) end
end

_omagen_glitch_timer = hl.timer(function()
  if _omagen_glitch_cleanup then _omagen_glitch_cleanup() end
end, { timeout = 1250, type = "repeat" })
_omagen_glitch_timer:set_enabled(false)
hl.on("window.open", function() _omagen_glitch_burst() end)
hl.on("window.close", function() _omagen_glitch_burst() end)
hl.on("window.urgent", function() _omagen_glitch_burst() end)
hl.on("workspace.active", function() _omagen_glitch_burst() end)
local _omagen_native_shell_signal_namespaces = { ["omarchy-menu"] = true, ["omarchy-image-selector"] = true, ["omarchy-emojis"] = true, ["omarchy-clipboard"] = true, ["omarchy-keyboard-panel"] = true, ["omarchy-notifications"] = true, ["omarchy-osd"] = true, ["omarchy-polkit"] = true, ["omarchy-network-qr"] = true, ["omarchy-reminders"] = true, ["omarchy-lock-preview"] = true, ["omagen-notification-signal"] = true, ["omagen-background-signal"] = true }
local _omagen_native_shell_signal = function(layer)
  if not layer then return false end
  if _omagen_native_shell_signal_namespaces[layer.namespace] == true then return true end
  local namespace = tostring(layer.namespace or "")
  if string.find(namespace, "omagen-notification-signal-", 1, true) == 1 then return true end
  return string.find(namespace, "omagen-background-signal-", 1, true) == 1
end
hl.on("layer.opened", function(layer) if _omagen_native_shell_signal(layer) then _omagen_glitch_burst() end end)
hl.layer_rule({ name = "omagen-cyberpunk-native-shell-motion", match = { namespace = "^omarchy-(menu|image-selector|emojis|clipboard|keyboard-panel|notifications|osd|polkit|network-qr|reminders|lock-preview)$" }, no_anim = false, animation = "slide" })
