foreground #ffc8c6
background #0d0506
selection_foreground #fff6f6
selection_background #45111b

cursor #fff6f6
cursor_text_color #0d0506

active_border_color #de555d
active_tab_background #de555d

color0 #0d0506
color1 #c64b5c
color2 #c84a5c
color3 #c44d5d
color4 #c9475a
color5 #c34f5e
color6 #c54d5d
color7 #ffc8c6
color8 #715555
color9 #ee5f72
color10 #ec6173
color11 #f05d71
color12 #ed6173
color13 #f15b70
color14 #f05e72
color15 #fff6f6
