#!/bin/bash
# Hook triggered on Omarchy theme-set to sync theme colors to ytkew
# Adheres strictly to Omarchy dark/light contrast guidelines.

set -euo pipefail

THEME_NAME="${1:-}"
YTKEW_THEMES_DIR="$HOME/.config/ytkew/themes"
mkdir -p "$YTKEW_THEMES_DIR"

# Query theme parameters via omarchy-theme-env if available
if command -v omarchy-theme-env &>/dev/null; then
  THEME_JSON=$(omarchy-theme-env --json 2>/dev/null || echo "{}")
  MODE=$(echo "$THEME_JSON" | jq -r '.mode // "dark"')
  FG=$(echo "$THEME_JSON" | jq -r '.foreground // "#b9bec6"')
  BG=$(echo "$THEME_JSON" | jq -r '.background // "#181a1f"')
  ACCENT=$(echo "$THEME_JSON" | jq -r '.accent // "#ad2222"')
else
  MODE="${OMARCHY_THEME_MODE:-dark}"
  FG="${OMARCHY_THEME_FG:-#b9bec6}"
  BG="${OMARCHY_THEME_BG:-#181a1f}"
  ACCENT="${OMARCHY_THEME_ACCENT:-#ad2222}"
fi

# Apply strict Omarchy dual-mode contrast rules:
if [[ "$MODE" == "light" ]]; then
  # Light mode:
  # - dark: distinct border/chrome (medium-dark slate/gray)
  # - mid: high-contrast dark text (never white/dim)
  # - bright: rich, saturated accent
  DARK="#8a8f98"
  MID="#2b2d31"
  BRIGHT="$ACCENT"
else
  # Dark mode:
  # - dark: subtle dark borders / chrome
  # - mid: primary / secondary foreground text
  # - bright: active theme accent
  DARK="#3e4451"
  MID="$FG"
  BRIGHT="$ACCENT"
fi

cat <<TOML > "$YTKEW_THEMES_DIR/omarchy.toml"
# Auto-generated by Omarchy theme-set hook for theme: ${THEME_NAME:-active}
name   = "omarchy"
dark   = "$DARK"
mid    = "$MID"
bright = "$BRIGHT"
TOML

chmod 644 "$YTKEW_THEMES_DIR/omarchy.toml"
