#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

# hyprlock.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

$color = rgba(11, 13, 17, 1)
$inner_color = rgba(11, 13, 17, 0.66)
$outer_color = rgba(242, 56, 136, 1)
$font_color = rgba(240, 183, 202, 1)
$placeholder_color = rgba(240, 183, 202, 0.7)
$check_color = rgba(90, 161, 93, 1)

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/
#                               