--  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
-- |                                                   |
-- |   ,---.          ,--.                             |
-- |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
-- |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
-- |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
-- |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
-- |                 . .         . .                   |
-- |               .-^~^-.     .-^~^-.                 |
-- |               `-._.-'     `-._.-'                 |
-- |                  |           |                    |
-- |     ,--.   ,--.             ,--.     ,--.         |
-- |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
-- |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
-- |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
-- |     `--'   `--' `---'  `---'`--' `--'`--'         |
-- |                                                   |
--  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-sakura-mochi-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(f23888ee)", "rgba(f0b7cacc)", "rgba(67dd82aa)" },
  angle = 35,
}
local inactiveBorderColor = "rgba(5aa15d99)"
local shadowColor = "rgba(0b0d118c)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 12,
    gaps_out = 24,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    active_opacity = 0.97,
    inactive_opacity = 0.95,
    rounding = 14,
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      ignore_opacity = true,
      new_optimizations = true,
      xray = false,
      noise = 0.03,
      contrast = 0.87,
      vibrancy = 0.03,
      vibrancy_darkness = 0.7,
      brightness = 0.42,
      popups_ignorealpha = 0.5,
      input_methods_ignorealpha = 0.5,
    },
    shadow = {
      enabled = true,
      range = 16,
      render_power = 3,
      color = shadowColor,
      color_inactive = shadowColor,
      offset = "2 2",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("mochiFloat", { type = "bezier", points = { { 0.22, 0.9 }, { 0.2, 1.0 } } })
hl.curve("sakuraDrift", { type = "bezier", points = { { 0.3, 1.05 }, { 0.38, 1.0 } } })
hl.curve("glassFade", { type = "bezier", points = { { 0.18, 0.0 }, { 0.12, 1.0 } } })
hl.curve("workspaceGlide", { type = "bezier", points = { { 0.23, 0.84 }, { 0.34, 1.0 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "mochiFloat",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 5,
  bezier = "sakuraDrift",
  style = "popin 10%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 4,
  bezier = "glassFade",
  style = "popin 82%",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 5,
  bezier = "mochiFloat",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 6,
  bezier = "glassFade",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 5,
  bezier = "glassFade",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 5,
  bezier = "sakuraDrift",
  style = "slidefade",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 5,
  bezier = "sakuraDrift",
  style = "slidefade",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 4,
  bezier = "glassFade",
  style = "fade",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 7,
  bezier = "workspaceGlide",
  style = "slide",
})

--   ____  __   __
--  / __ \/ /__/ /
-- / /_/ / / _  / 
-- \____/_/\_,_/  
--      __     __        __      
--  __ / /__  / /  ___  / /  ___ 
-- / // / _ \/ _ \/ _ \/ _ \/ _ \
-- \___/\___/_.__/\___/_.__/\___/
--                               