.pragma library

var allShortcuts = [
  { key: "SUPER SHIFT + K", desc: "Classic Keybindings Menu", category: "system", icon: "󰍜", action: "omarchy-menu-keybindings" },
  { key: "SUPER + SPACE", desc: "Omarchy menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle" },
  { key: "SUPER + RETURN", desc: "Terminal", category: "apps", icon: "󰞷", action: "omarchy-launch-terminal" },
  { key: "SUPER SHIFT + RETURN", desc: "Browser", category: "apps", icon: "󰖟", action: "omarchy-launch-browser" },
  { key: "SUPER SHIFT + F", desc: "File manager", category: "apps", icon: "󰉋", action: "omarchy-launch-nautilus" },
  { key: "SUPER + ESCAPE", desc: "System menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle system" },
  { key: "SUPER SHIFT CTRL + SPACE", desc: "Theme menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle theme" },
  { key: "SUPER + F", desc: "Full screen", category: "other", icon: "󰌌", action: "hyprctl dispatch \"hl.dsp.window.fullscreen({ mode = \"fullscreen\" })\"" },
  { key: "SUPER ALT + F", desc: "Full width", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.fullscreen({ mode = \"maximized\" })\"" },
  { key: "SUPER + W", desc: "Close window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.close()\"" },
  { key: "CTRL ALT + DELETE", desc: "Close all windows", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-close-all" },
  { key: "SUPER CTRL + L", desc: "Lock system", category: "system", icon: "󰐥", action: "omarchy-system-lock" },
  { key: "SUPER + T", desc: "Toggle window floating/tiling", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.float({ action = \"toggle\" })\"" },
  { key: "SUPER + J", desc: "Toggle window split", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.layout(\"togglesplit\")\"" },
  { key: "SUPER + O", desc: "Pop window out (float & pin)", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-pop" },
  { key: "SUPER + C", desc: "Universal copy", category: "tools", icon: "󰅌", action: "" },
  { key: "SUPER + V", desc: "Universal paste", category: "tools", icon: "󰅌", action: "" },
  { key: "SUPER + X", desc: "Universal cut", category: "tools", icon: "󰅌", action: "" },
  { key: "SUPER CTRL + V", desc: "Clipboard manager", category: "tools", icon: "󰅌", action: "omarchy-shell shell toggle omarchy.clipboard" },
  { key: "SUPER CTRL + E", desc: "Emojis", category: "other", icon: "󰌌", action: "omarchy-shell shell toggle omarchy.emojis" },
  { key: "SUPER + PRINT", desc: "Color picker", category: "tools", icon: "󰹉", action: "pkill hyprpicker || hyprpicker -a" },
  { key: "PRINT", desc: "Screenshot", category: "tools", icon: "󰹉", action: "omarchy-capture-screenshot" },
  { key: "ALT + PRINT", desc: "Screenrecording", category: "tools", icon: "󰹉", action: "omarchy-capture-screenrecording --stop-recording || omarchy-menu toggle trigger.capture.screenrecord" },
  { key: "SUPER ALT + RETURN", desc: "Tmux", category: "apps", icon: "󰞷", action: "omarchy-launch-terminal-tmux" },
  { key: "SUPER CTRL + RETURN", desc: "Herdr", category: "apps", icon: "󰞷", action: "omarchy-launch-terminal-herdr" },
  { key: "SUPER SHIFT ALT + B", desc: "Browser (private)", category: "apps", icon: "󰖟", action: "omarchy-launch-browser --private" },
  { key: "SUPER SHIFT + B", desc: "Browser", category: "apps", icon: "󰖟", action: "omarchy-launch-browser" },
  { key: "SUPER SHIFT ALT + F", desc: "File manager (cwd)", category: "apps", icon: "󰉋", action: "omarchy-launch-nautilus-cwd" },
  { key: "SUPER + 0", desc: "Switch to workspace 10", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"10\" })\"" },
  { key: "SUPER + 1", desc: "Switch to workspace 1", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"1\" })\"" },
  { key: "SUPER + 2", desc: "Switch to workspace 2", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"2\" })\"" },
  { key: "SUPER + 3", desc: "Switch to workspace 3", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"3\" })\"" },
  { key: "SUPER + 4", desc: "Switch to workspace 4", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"4\" })\"" },
  { key: "SUPER + 5", desc: "Switch to workspace 5", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"5\" })\"" },
  { key: "SUPER + 6", desc: "Switch to workspace 6", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"6\" })\"" },
  { key: "SUPER + 7", desc: "Switch to workspace 7", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"7\" })\"" },
  { key: "SUPER + 8", desc: "Switch to workspace 8", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"8\" })\"" },
  { key: "SUPER + 9", desc: "Switch to workspace 9", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"9\" })\"" },
  { key: "SUPER CTRL + TAB", desc: "Former workspace", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"previous\" })\"" },
  { key: "SUPER SHIFT + TAB", desc: "Previous workspace", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"e-1\" })\"" },
  { key: "SUPER + TAB", desc: "Next workspace", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"e+1\" })\"" },
  { key: "SUPER SHIFT + 0", desc: "Move window to workspace 10", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"10\" })\"" },
  { key: "SUPER SHIFT + 1", desc: "Move window to workspace 1", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"1\" })\"" },
  { key: "SUPER SHIFT + 2", desc: "Move window to workspace 2", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"2\" })\"" },
  { key: "SUPER SHIFT + 3", desc: "Move window to workspace 3", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"3\" })\"" },
  { key: "SUPER SHIFT + 4", desc: "Move window to workspace 4", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"4\" })\"" },
  { key: "SUPER SHIFT + 5", desc: "Move window to workspace 5", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"5\" })\"" },
  { key: "SUPER SHIFT + 6", desc: "Move window to workspace 6", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"6\" })\"" },
  { key: "SUPER SHIFT + 7", desc: "Move window to workspace 7", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"7\" })\"" },
  { key: "SUPER SHIFT + 8", desc: "Move window to workspace 8", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"8\" })\"" },
  { key: "SUPER SHIFT + 9", desc: "Move window to workspace 9", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ workspace = \"9\" })\"" },
  { key: "SUPER SHIFT ALT + 0", desc: "Move window silently to workspace 10", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"10\" })\"" },
  { key: "SUPER SHIFT ALT + 1", desc: "Move window silently to workspace 1", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"1\" })\"" },
  { key: "SUPER SHIFT ALT + 2", desc: "Move window silently to workspace 2", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"2\" })\"" },
  { key: "SUPER SHIFT ALT + 3", desc: "Move window silently to workspace 3", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"3\" })\"" },
  { key: "SUPER SHIFT ALT + 4", desc: "Move window silently to workspace 4", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"4\" })\"" },
  { key: "SUPER SHIFT ALT + 5", desc: "Move window silently to workspace 5", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"5\" })\"" },
  { key: "SUPER SHIFT ALT + 6", desc: "Move window silently to workspace 6", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"6\" })\"" },
  { key: "SUPER SHIFT ALT + 7", desc: "Move window silently to workspace 7", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"7\" })\"" },
  { key: "SUPER SHIFT ALT + 8", desc: "Move window silently to workspace 8", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"8\" })\"" },
  { key: "SUPER SHIFT ALT + 9", desc: "Move window silently to workspace 9", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"9\" })\"" },
  { key: "SUPER SHIFT + DOWN", desc: "Swap window down", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.swap({ direction = \"d\" })\"" },
  { key: "SUPER SHIFT + LEFT", desc: "Swap window to the left", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.swap({ direction = \"l\" })\"" },
  { key: "SUPER SHIFT + RIGHT", desc: "Swap window to the right", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.swap({ direction = \"r\" })\"" },
  { key: "SUPER SHIFT + UP", desc: "Swap window up", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.swap({ direction = \"u\" })\"" },
  { key: "ALT + TAB", desc: "Focus on next window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.cycle_next()\"" },
  { key: "CTRL ALT + TAB", desc: "Focus on next monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ monitor = \"+1\" })\"" },
  { key: "SHIFT ALT + TAB", desc: "Focus on previous window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.cycle_next({ next = false })\"" },
  { key: "SHIFT CTRL ALT + TAB", desc: "Focus on previous monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ monitor = \"-1\" })\"" },
  { key: "SUPER + DOWN", desc: "Focus on below window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.focus({ direction = \"d\" })\"" },
  { key: "SUPER + LEFT", desc: "Focus on left window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.focus({ direction = \"l\" })\"" },
  { key: "SUPER + RIGHT", desc: "Focus on right window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.focus({ direction = \"r\" })\"" },
  { key: "SUPER + UP", desc: "Focus on above window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.focus({ direction = \"u\" })\"" },
  { key: "SUPER + LEFT MOUSE BUTTON", desc: "Move window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.drag()\"" },
  { key: "SUPER + RIGHT MOUSE BUTTON", desc: "Resize window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize()\"" },
  { key: "SUPER ALT + MINUS", desc: "Expand window left a little", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = -25, y = 0 })\"" },
  { key: "SUPER CTRL + MINUS", desc: "Expand window left a lot", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = -300, y = 0 })\"" },
  { key: "SUPER + MINUS", desc: "Expand window left", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = -100, y = 0 })\"" },
  { key: "SUPER SHIFT ALT + EQUAL", desc: "Expand window down a little", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = 25 })\"" },
  { key: "SUPER SHIFT CTRL + EQUAL", desc: "Expand window down a lot", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = 300 })\"" },
  { key: "SUPER SHIFT + EQUAL", desc: "Expand window down", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = 100 })\"" },
  { key: "SUPER ALT + EQUAL", desc: "Shrink window left a little", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 25, y = 0 })\"" },
  { key: "SUPER CTRL + EQUAL", desc: "Shrink window left a lot", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 300, y = 0 })\"" },
  { key: "SUPER + EQUAL", desc: "Shrink window left", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 100, y = 0 })\"" },
  { key: "SUPER SHIFT ALT + MINUS", desc: "Shrink window up a little", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = -25 })\"" },
  { key: "SUPER SHIFT CTRL + MINUS", desc: "Shrink window up a lot", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = -300 })\"" },
  { key: "SUPER SHIFT + MINUS", desc: "Shrink window up", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.resize({ relative = true, x = 0, y = -100 })\"" },
  { key: "SUPER ALT + S", desc: "Move window to scratchpad", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ follow = false, workspace = \"special:scratchpad\" })\"" },
  { key: "SUPER + S", desc: "Toggle scratchpad", category: "workspace", icon: "󰖮", action: "hyprctl dispatch \"hl.dsp.workspace.toggle_special(\"scratchpad\")\"" },
  { key: "SUPER ALT + COMMA", desc: "Invoke last notification", category: "system", icon: "󰂛", action: "omarchy-shell notifications invokeLast" },
  { key: "SUPER + COMMA", desc: "Dismiss last notification", category: "system", icon: "󰂛", action: "omarchy-shell notifications dismissOne" },
  { key: "SUPER CTRL + COMMA", desc: "Toggle silencing notifications", category: "system", icon: "󰂛", action: "omarchy-toggle-notification-silencing" },
  { key: "SUPER SHIFT ALT + COMMA", desc: "Open notification history", category: "system", icon: "󰂛", action: "omarchy-shell notifications showHistory" },
  { key: "SUPER SHIFT + COMMA", desc: "Dismiss all notifications", category: "system", icon: "󰂛", action: "omarchy-shell notifications dismissAll" },
  { key: "SUPER + BACKSPACE", desc: "Toggle window transparency", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-transparency-toggle" },
  { key: "SUPER CTRL + N", desc: "Toggle nightlight", category: "system", icon: "󰐥", action: "omarchy-toggle-nightlight" },
  { key: "SUPER CTRL + I", desc: "Toggle locking on idle", category: "system", icon: "󰐥", action: "omarchy-toggle-idle" },
  { key: "F9", desc: "Start/stop dictation (push-to-talk)", category: "tools", icon: "󰃬", action: "voxtype record toggle" },
  { key: "SHIFT ALT + D", desc: "Download Video from Web App", category: "apps", icon: "󰖟", action: "hyprctl dispatch sendshortcut \"SHIFT ALT,D,\"" },
  { key: "SHIFT ALT + L", desc: "Copy URL from Web App", category: "apps", icon: "󰖟", action: "hyprctl dispatch sendshortcut \"SHIFT ALT,L,\"" },
  { key: "SUPER ALT + A", desc: "Antigravity", category: "other", icon: "󰌌", action: "omarchy-launch-or-focus '^antigravity$' 'uwsm-app -- antigravity'" },
  { key: "SUPER ALT + BACKSPACE", desc: "Select window gap mode", category: "window", icon: "󰉦", action: "omarchy-gap-mode menu" },
  { key: "SUPER ALT + BRACKETLEFT", desc: "Make webcam overlay smaller", category: "other", icon: "󰌌", action: "omarchy-capture-webcam-resize smaller" },
  { key: "SUPER ALT + BRACKETRIGHT", desc: "Make webcam overlay larger", category: "other", icon: "󰌌", action: "omarchy-capture-webcam-resize larger" },
  { key: "SUPER ALT + Home", desc: "Save window width", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-width save" },
  { key: "SUPER ALT + SLASH", desc: "Monitor scaling down", category: "workspace", icon: "󱂬", action: "omarchy-hyprland-monitor-scaling down" },
  { key: "SUPER ALT + SPACE", desc: "Apps menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle apps" },
  { key: "SUPER CTRL + 1", desc: "Bar panel 1", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 1" },
  { key: "SUPER CTRL + 2", desc: "Bar panel 2", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 2" },
  { key: "SUPER CTRL + 3", desc: "Bar panel 3", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 3" },
  { key: "SUPER CTRL + 4", desc: "Bar panel 4", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 4" },
  { key: "SUPER CTRL + 5", desc: "Bar panel 5", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 5" },
  { key: "SUPER CTRL + 6", desc: "Bar panel 6", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 6" },
  { key: "SUPER CTRL + 7", desc: "Bar panel 7", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 7" },
  { key: "SUPER CTRL + 8", desc: "Bar panel 8", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 8" },
  { key: "SUPER CTRL + 9", desc: "Bar panel 9", category: "system", icon: "󰐥", action: "omarchy-shell -q shell togglePanelAt right 9" },
  { key: "SUPER CTRL + A", desc: "Audio", category: "media", icon: "󰕾", action: "omarchy-shell shell toggle omarchy.audio" },
  { key: "SUPER CTRL ALT + B", desc: "Show battery remaining", category: "system", icon: "󰐥", action: "omarchy-notification-battery" },
  { key: "SUPER CTRL ALT + D", desc: "Calendar", category: "other", icon: "󰌌", action: "omarchy-shell shell toggle omarchy.clock" },
  { key: "SUPER CTRL ALT + Delete", desc: "Toggle laptop display mirroring", category: "system", icon: "󰐥", action: "omarchy-hyprland-monitor-internal-mirror toggle" },
  { key: "SUPER CTRL ALT + R", desc: "Show reminders", category: "tools", icon: "󰃬", action: "omarchy-reminder show" },
  { key: "SUPER CTRL ALT + T", desc: "Show time", category: "other", icon: "󰌌", action: "omarchy-notification-time" },
  { key: "SUPER CTRL ALT + W", desc: "Toggle weather", category: "other", icon: "󰌌", action: "omarchy-notification-weather" },
  { key: "SUPER CTRL ALT + Z", desc: "Reset zoom", category: "tools", icon: "󰃬", action: "" },
  { key: "SUPER CTRL + BACKSPACE", desc: "Toggle single-window square aspect", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-single-square-aspect-toggle" },
  { key: "SUPER CTRL + B", desc: "Bluetooth", category: "system", icon: "󰐥", action: "omarchy-shell shell toggle omarchy.bluetooth" },
  { key: "SUPER CTRL + C", desc: "Capture menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle capture" },
  { key: "SUPER CTRL + D", desc: "Display", category: "system", icon: "󰐥", action: "omarchy-shell shell toggle omarchy.monitor" },
  { key: "SUPER CTRL + Delete", desc: "Toggle laptop display", category: "system", icon: "󰐥", action: "omarchy-hyprland-monitor-internal toggle" },
  { key: "SUPER CTRL + F", desc: "Tiled full screen", category: "other", icon: "󰌌", action: "omarchy-hyprland-window-tiled-fullscreen-toggle" },
  { key: "SUPER CTRL + H", desc: "Hardware menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle hardware" },
  { key: "SUPER CTRL + O", desc: "Toggle menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle toggle" },
  { key: "SUPER CTRL + PERIOD", desc: "Transcode", category: "other", icon: "󰌌", action: "omarchy-transcode" },
  { key: "SUPER CTRL + P", desc: "Power", category: "system", icon: "󰐥", action: "omarchy-shell shell toggle omarchy.power" },
  { key: "SUPER CTRL + PRINT", desc: "Extract text (OCR) from screenshot", category: "tools", icon: "󰹉", action: "omarchy-capture-text" },
  { key: "SUPER CTRL + Q", desc: "Calculator", category: "tools", icon: "󰃬", action: "omacalc" },
  { key: "SUPER CTRL + R", desc: "Set reminder", category: "tools", icon: "󰃬", action: "omarchy-menu toggle reminder-set" },
  { key: "SUPER CTRL + SPACE", desc: "Background switcher", category: "other", icon: "󰌌", action: "omarchy-menu toggle background" },
  { key: "SUPER CTRL + S", desc: "Share", category: "other", icon: "󰌌", action: "omarchy-menu toggle share" },
  { key: "SUPER CTRL + T", desc: "Activity", category: "other", icon: "󰌌", action: "omarchy-launch-tui 'btop'" },
  { key: "SUPER CTRL + W", desc: "Network", category: "system", icon: "󰐥", action: "omarchy-shell shell toggle omarchy.network" },
  { key: "SUPER CTRL + X", desc: "Toggle dictation", category: "tools", icon: "󰃬", action: "voxtype record toggle" },
  { key: "SUPER CTRL + Z", desc: "Zoom in", category: "tools", icon: "󰃬", action: "" },
  { key: "SUPER + Home", desc: "Restore window width", category: "window", icon: "󰉦", action: "omarchy-hyprland-window-width restore" },
  { key: "SUPER + K", desc: "Navigation Guide", category: "other", icon: "󰌌", action: "omarchy-shell nav-guide toggle" },
  { key: "SUPER + L", desc: "Toggle workspace layout", category: "workspace", icon: "󱂬", action: "omarchy-hyprland-workspace-layout-toggle" },
  { key: "SUPER + P", desc: "Pseudo window", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.pseudo()\"" },
  { key: "SUPER SHIFT ALT + A", desc: "Grok", category: "apps", icon: "󰖟", action: "omarchy-launch-webapp 'https://grok.com'" },
  { key: "SUPER SHIFT ALT + DOWN", desc: "Move workspace to down monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.workspace.move({ monitor = \"d\" })\"" },
  { key: "SUPER SHIFT ALT + E", desc: "New email", category: "other", icon: "󰌌", action: "omarchy-launch-webapp 'https://app.hey.com/messages/new?display=standalone&new_window=true'" },
  { key: "SUPER SHIFT ALT + G", desc: "WhatsApp", category: "apps", icon: "󰖟", action: "omarchy-launch-or-focus-webapp 'WhatsApp' 'https://web.whatsapp.com/'" },
  { key: "SUPER SHIFT ALT + LEFT", desc: "Move workspace to left monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.workspace.move({ monitor = \"l\" })\"" },
  { key: "SUPER SHIFT ALT + M", desc: "Music TUI", category: "media", icon: "󰕾", action: "omarchy-launch-or-focus-tui 'cliamp'" },
  { key: "SUPER SHIFT ALT + RIGHT", desc: "Move workspace to right monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.workspace.move({ monitor = \"r\" })\"" },
  { key: "SUPER SHIFT ALT + UP", desc: "Move workspace to up monitor", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.workspace.move({ monitor = \"u\" })\"" },
  { key: "SUPER SHIFT ALT + X", desc: "X Post", category: "apps", icon: "󰖟", action: "omarchy-launch-webapp 'https://x.com/compose/post'" },
  { key: "SUPER SHIFT + BACKSPACE", desc: "Cycle window gap mode", category: "window", icon: "󰉦", action: "omarchy-gap-mode cycle" },
  { key: "SUPER SHIFT + C", desc: "Calendar", category: "other", icon: "󰌌", action: "omarchy-launch-webapp 'https://app.hey.com/calendar/weeks/'" },
  { key: "SUPER SHIFT CTRL + A", desc: "Agent", category: "other", icon: "󰌌", action: "omarchy-agent --pick" },
  { key: "SUPER SHIFT CTRL + G", desc: "Google Messages", category: "other", icon: "󰌌", action: "omarchy-launch-or-focus-webapp 'Google Messages' 'https://messages.google.com/web/conversations'" },
  { key: "SUPER SHIFT CTRL + R", desc: "Clear reminders", category: "tools", icon: "󰃬", action: "omarchy-reminder clear" },
  { key: "SUPER SHIFT + D", desc: "Docker", category: "other", icon: "󰌌", action: "omarchy-launch-tui 'omarchy-launch-docker-tui'" },
  { key: "SUPER SHIFT + E", desc: "Email", category: "other", icon: "󰌌", action: "omarchy-launch-webapp 'https://app.hey.com'" },
  { key: "SUPER SHIFT + G", desc: "Signal", category: "apps", icon: "󰖟", action: "omarchy-launch-signal" },
  { key: "SUPER SHIFT + M", desc: "Music", category: "media", icon: "󰕾", action: "omarchy-launch-spotify" },
  { key: "SUPER SHIFT + N", desc: "Editor", category: "apps", icon: "󰈮", action: "omarchy-launch-editor" },
  { key: "SUPER SHIFT + O", desc: "Obsidian", category: "apps", icon: "󰈮", action: "omarchy-launch-or-focus '^obsidian$' 'uwsm-app -- obsidian'" },
  { key: "SUPER SHIFT + P", desc: "Google Photos", category: "other", icon: "󰌌", action: "omarchy-launch-or-focus-webapp 'Google Photos' 'https://photos.google.com/'" },
  { key: "SUPER SHIFT + S", desc: "Google Maps", category: "other", icon: "󰌌", action: "omarchy-launch-or-focus-webapp 'Google Maps' 'https://maps.google.com/'" },
  { key: "SUPER SHIFT + SLASH", desc: "Passwords", category: "tools", icon: "󰃬", action: "omarchy-launch-1password" },
  { key: "SUPER SHIFT + SPACE", desc: "Toggle top bar", category: "system", icon: "󰐥", action: "omarchy-toggle-bar" },
  { key: "SUPER SHIFT + W", desc: "Omawrite", category: "apps", icon: "󰈮", action: "uwsm-app -- omawrite" },
  { key: "SUPER SHIFT + X", desc: "X", category: "other", icon: "󰌌", action: "omarchy-launch-webapp 'https://x.com/'" },
  { key: "SUPER SHIFT + Y", desc: "YouTube", category: "other", icon: "󰌌", action: "omarchy-launch-webapp 'https://youtube.com/'" },
  { key: "SUPER + SLASH", desc: "Monitor scaling up", category: "workspace", icon: "󱂬", action: "omarchy-hyprland-monitor-scaling up" },
  { key: "SUPER ALT + 1", desc: "Switch to group window 1", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.active({ index = 1 })\"" },
  { key: "SUPER ALT + 2", desc: "Switch to group window 2", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.active({ index = 2 })\"" },
  { key: "SUPER ALT + 3", desc: "Switch to group window 3", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.active({ index = 3 })\"" },
  { key: "SUPER ALT + 4", desc: "Switch to group window 4", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.active({ index = 4 })\"" },
  { key: "SUPER ALT + 5", desc: "Switch to group window 5", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.active({ index = 5 })\"" },
  { key: "SUPER ALT + DOWN", desc: "Move window to group on bottom", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ into_group = \"d\" })\"" },
  { key: "SUPER ALT + G", desc: "Move active window out of group", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ out_of_group = true })\"" },
  { key: "SUPER ALT + LEFT", desc: "Move window to group on left", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ into_group = \"l\" })\"" },
  { key: "SUPER ALT + mouse_down", desc: "Next window in group", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.next()\"" },
  { key: "SUPER ALT + mouse_up", desc: "Previous window in group", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.prev()\"" },
  { key: "SUPER ALT + RIGHT", desc: "Move window to group on right", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ into_group = \"r\" })\"" },
  { key: "SUPER ALT + TAB", desc: "Next window in group", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.next()\"" },
  { key: "SUPER ALT + UP", desc: "Move window to group on top", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.move({ into_group = \"u\" })\"" },
  { key: "SUPER CTRL + LEFT", desc: "Move grouped window focus left", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.prev()\"" },
  { key: "SUPER CTRL + RIGHT", desc: "Move grouped window focus right", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.next()\"" },
  { key: "SUPER + G", desc: "Toggle window grouping", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.toggle()\"" },
  { key: "SUPER SHIFT ALT + TAB", desc: "Previous window in group", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.group.prev()\"" },
  { key: "SUPER + mouse_down", desc: "Scroll active workspace forward", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"e+1\" })\"" },
  { key: "SUPER + mouse_up", desc: "Scroll active workspace backward", category: "workspace", icon: "󱂬", action: "hyprctl dispatch \"hl.dsp.focus({ workspace = \"e-1\" })\"" },
  { key: "ALT + TAB", desc: "Reveal active window on top", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.bring_to_top()\"" },
  { key: "SHIFT ALT + TAB", desc: "Reveal active window on top", category: "window", icon: "󰉦", action: "hyprctl dispatch \"hl.dsp.window.bring_to_top()\"" },
  { key: "ALT + XF86AudioLowerVolume", desc: "Volume down precise", category: "media", icon: "󰕾", action: "omarchy-audio-output-volume -1" },
  { key: "ALT + XF86AudioPlay", desc: "Next track", category: "other", icon: "󰌌", action: "omarchy-shell media next" },
  { key: "ALT + XF86AudioRaiseVolume", desc: "Volume up precise", category: "media", icon: "󰕾", action: "omarchy-audio-output-volume +1" },
  { key: "ALT + XF86MonBrightnessDown", desc: "Brightness down precise", category: "other", icon: "󰌌", action: "omarchy-brightness-display 1%-" },
  { key: "ALT + XF86MonBrightnessUp", desc: "Brightness up precise", category: "other", icon: "󰌌", action: "omarchy-brightness-display +1%" },
  { key: "SHIFT ALT + XF86AudioPlay", desc: "Previous track", category: "other", icon: "󰌌", action: "omarchy-shell media previous" },
  { key: "SHIFT + XF86AudioMute", desc: "Switch audio output", category: "media", icon: "󰕾", action: "omarchy-audio-output-switch" },
  { key: "SHIFT + XF86AudioPause", desc: "Switch media source", category: "other", icon: "󰌌", action: "omarchy-audio-source-switch" },
  { key: "SHIFT + XF86AudioPlay", desc: "Switch media source", category: "other", icon: "󰌌", action: "omarchy-audio-source-switch" },
  { key: "SHIFT + XF86MonBrightnessDown", desc: "Brightness minimum", category: "other", icon: "󰌌", action: "omarchy-brightness-display 1%" },
  { key: "SHIFT + XF86MonBrightnessUp", desc: "Brightness maximum", category: "other", icon: "󰌌", action: "omarchy-brightness-display 100%" },
  { key: "XF86AudioLowerVolume", desc: "Volume down", category: "media", icon: "󰕾", action: "omarchy-audio-output-volume lower" },
  { key: "XF86AudioMicMute", desc: "Mute microphone", category: "media", icon: "󰕾", action: "omarchy-audio-input-mute" },
  { key: "XF86AudioMute", desc: "Mute", category: "other", icon: "󰌌", action: "omarchy-audio-output-volume mute-toggle" },
  { key: "XF86AudioNext", desc: "Next track", category: "other", icon: "󰌌", action: "omarchy-shell media next" },
  { key: "XF86AudioPause", desc: "Pause", category: "other", icon: "󰌌", action: "omarchy-shell media playPause" },
  { key: "XF86AudioPlay", desc: "Play", category: "other", icon: "󰌌", action: "omarchy-shell media playPause" },
  { key: "XF86AudioPrev", desc: "Previous track", category: "other", icon: "󰌌", action: "omarchy-shell media previous" },
  { key: "XF86AudioRaiseVolume", desc: "Volume up", category: "media", icon: "󰕾", action: "omarchy-audio-output-volume raise" },
  { key: "XF86Calculator", desc: "Calculator", category: "tools", icon: "󰃬", action: "omacalc" },
  { key: "XF86Eject", desc: "Eject media", category: "other", icon: "󰌌", action: "eject" },
  { key: "XF86KbdBrightnessDown", desc: "Keyboard brightness down", category: "other", icon: "󰌌", action: "omarchy-brightness-keyboard down" },
  { key: "XF86KbdBrightnessUp", desc: "Keyboard brightness up", category: "other", icon: "󰌌", action: "omarchy-brightness-keyboard up" },
  { key: "XF86KbdLightOnOff", desc: "Keyboard backlight cycle", category: "other", icon: "󰌌", action: "omarchy-brightness-keyboard cycle" },
  { key: "XF86MonBrightnessDown", desc: "Brightness down", category: "other", icon: "󰌌", action: "omarchy-brightness-display 5%-" },
  { key: "XF86MonBrightnessUp", desc: "Brightness up", category: "other", icon: "󰌌", action: "omarchy-brightness-display +5%" },
  { key: "XF86PowerOff", desc: "Power menu", category: "system", icon: "󰍜", action: "omarchy-menu toggle system" },
  { key: "XF86TouchpadOff", desc: "Disable touchpad", category: "other", icon: "󰌌", action: "omarchy-toggle-touchpad off" },
  { key: "XF86TouchpadOn", desc: "Enable touchpad", category: "other", icon: "󰌌", action: "omarchy-toggle-touchpad on" },
  { key: "XF86TouchpadToggle", desc: "Toggle touchpad", category: "other", icon: "󰌌", action: "omarchy-toggle-touchpad" },
  { key: "SUPER ALT + K", desc: "Tmux keybindings", category: "apps", icon: "󰞷", action: "omarchy-menu-tmux-keybindings" },
  { key: "SUPER CTRL + K", desc: "Herdr keybindings", category: "apps", icon: "󰞷", action: "omarchy-menu-herdr-keybindings" }
];
