-- Generated by wmfeht.border-fx (look-apply). Do not edit.
-- Source of truth: ~/.config/omarchy/shell.json plugins[] entry id wmfeht.border-fx.
-- Effect "shiny" fans out to the Hyprland adapter (plugin:shiny-border / shiny_border) when effect is shiny or ripple.

hl.permission({ binary = "/usr/(bin|local/bin)/hyprctl", type = "plugin", mode = "allow" })

local SHINY_SO = "/home/soham/.local/lib/hypr/hypr-shiny-border.so"
local SHINY_LOAD = true

local function shinyLoaded()
  for _, p in ipairs(hl.get_loaded_plugins()) do
    if p.name == "hypr-shiny-border" then
      return true
    end
  end
  return false
end

-- Load on hyprland.start, not during parse: PLUGIN_INIT reloads config.
if SHINY_LOAD and not _G.__wmfeht_border_fx_start then
  _G.__wmfeht_border_fx_start = true
  hl.on("hyprland.start", function()
    if shinyLoaded() then
      return
    end
    local f = io.open(SHINY_SO, "r")
    if not f then
      return
    end
    f:close()
    hl.plugin.load(SHINY_SO)
  end)
end

if shinyLoaded() then
  hl.config({
    plugin = {
      shiny_border = {
        enabled      = true,
        effect       = "shiny",
        active_only  = true,
        pulse        = false,
        pulse_hz     = 0.4,
        ripple_freq  = 0.025,
        ripple_speed = 2,
        ripple_gain  = 0.85,
        ripple_power = 8,
        ripple_origin_x = 0.5,
        ripple_origin_y = 0.5,
        ripple_fade  = 0,
        shimmer      = true,
        shimmer_hz   = 0.28,
        shimmer_deg  = 22,
        shimmer_scale_min = 0.8,
        shimmer_scale_max = 1.4,
        pin_deg      = 120,
        angle_offset = 0,
        lobe         = 0.16,
        mirror       = true,
        specular_halo = false,
        border_size  = 2,
        col = {
          a = "rgba(f7ffffee)",
          b = "rgba(0a3f4700)",
        },
        base_color            = "rgba(0a3f47dd)",
        gradient              = { colors = { "rgba(f7ffffee)", "rgba(0a3f4700)" } },
        gradient_positions    = "0 99",
        gradient_cw           = { colors = { "rgba(f7ffffee)" } },
        gradient_positions_cw = "0 22 50 100",
      },
    },
  })
end