-- Generated by omarchy-sensei setup. Re-run setup instead of editing this file.
if hl and not _G.omarchy_sensei_original_hl_bind then
  _G.omarchy_sensei_original_hl_bind = hl.bind
  local coaching_by_description = {
    ["Herdr keybindings"] = { action = "herdr-keybindings", title = "Herdr keybindings" },
    ["Keybindings"] = { action = "keybindings", title = "Keybindings" },
    ["Tmux keybindings"] = { action = "tmux-keybindings", title = "Tmux keybindings" },
    ["Background switcher"] = { action = "background-switcher", title = "Background switcher" },
    ["Theme menu"] = { action = "theme-menu", title = "Theme menu" },
    ["Lock system"] = { action = "lock-system", title = "Lock system" },
    ["Color picker"] = { action = "color-picker", title = "Color picker" },
    ["Screenshot"] = { action = "screenshot", title = "Screenshot" },
    ["Extract text (OCR) from screenshot"] = { action = "extract-text-ocr-from-screenshot", title = "Extract text (OCR) from screenshot" },
    ["Emojis"] = { action = "emojis", title = "Emojis" },
    ["Toggle laptop display"] = { action = "toggle-laptop-display", title = "Toggle laptop display" },
    ["Toggle laptop display mirroring"] = { action = "toggle-laptop-display-mirroring", title = "Toggle laptop display mirroring" },
    ["Toggle touchpad"] = { action = "toggle-touchpad", title = "Toggle touchpad" },
    ["Clear reminders"] = { action = "clear-reminders", title = "Clear reminders" },
    ["Set reminder"] = { action = "set-reminder", title = "Set reminder" },
    ["Show reminders"] = { action = "show-reminders", title = "Show reminders" },
    ["Toggle locking on idle"] = { action = "toggle-locking-on-idle", title = "Toggle locking on idle" },
    ["Toggle nightlight"] = { action = "toggle-nightlight", title = "Toggle nightlight" },
    ["Toggle silencing notifications"] = { action = "toggle-silencing-notifications", title = "Toggle silencing notifications" },
    ["Toggle single-window square aspect"] = { action = "toggle-single-window-square-aspect", title = "Toggle single-window square aspect" },
    ["Toggle top bar"] = { action = "toggle-top-bar", title = "Toggle top bar" },
    ["Toggle window gaps"] = { action = "toggle-window-gaps", title = "Toggle window gaps" },
    ["Toggle workspace layout"] = { action = "toggle-workspace-layout", title = "Toggle workspace layout" },
    ["Transcode"] = { action = "transcode", title = "Transcode" },
    ["Omarchy menu"] = { action = "omarchy-menu", title = "Omarchy menu" },
    ["Terminal"] = { action = "terminal", title = "Terminal" },
    ["Browser"] = { action = "browser", title = "Browser" },
    ["File manager"] = { action = "file-manager", title = "File manager" },
    ["System menu"] = { action = "binding-711ecd0805fd", title = "System menu" },
    ["Full screen"] = { action = "full-screen", title = "Full screen" },
    ["Full width"] = { action = "full-width", title = "Full width" },
    ["Close window"] = { action = "close-window", title = "Close window" },
    ["Close all windows"] = { action = "close-all-windows", title = "Close all windows" },
    ["Toggle window floating/tiling"] = { action = "toggle-window-floating-tiling", title = "Toggle window floating/tiling" },
    ["Toggle window split"] = { action = "toggle-window-split", title = "Toggle window split" },
    ["Pop window out (float & pin)"] = { action = "pop-window-out-float-pin", title = "Pop window out (float & pin)" },
    ["Universal copy"] = { action = "universal-copy", title = "Universal copy" },
    ["Universal paste"] = { action = "universal-paste", title = "Universal paste" },
    ["Universal cut"] = { action = "universal-cut", title = "Universal cut" },
    ["Clipboard manager"] = { action = "clipboard-manager", title = "Clipboard manager" },
    ["Screenrecording"] = { action = "screenrecording", title = "Screenrecording" },
    ["Tmux"] = { action = "tmux", title = "Tmux" },
    ["Herdr"] = { action = "herdr", title = "Herdr" },
    ["Browser (private)"] = { action = "browser-private", title = "Browser (private)" },
    ["File manager (cwd)"] = { action = "file-manager-cwd", title = "File manager (cwd)" },
    ["Switch to workspace 10"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 1"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 2"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 3"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 4"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 5"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 6"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 7"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 8"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Switch to workspace 9"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Former workspace"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Move window to workspace 10"] = { action = "move-window-to-workspace-10", title = "Move window to workspace 10" },
    ["Move window to workspace 1"] = { action = "move-window-to-workspace-1", title = "Move window to workspace 1" },
    ["Move window to workspace 2"] = { action = "move-window-to-workspace-2", title = "Move window to workspace 2" },
    ["Move window to workspace 3"] = { action = "move-window-to-workspace-3", title = "Move window to workspace 3" },
    ["Move window to workspace 4"] = { action = "move-window-to-workspace-4", title = "Move window to workspace 4" },
    ["Move window to workspace 5"] = { action = "move-window-to-workspace-5", title = "Move window to workspace 5" },
    ["Move window to workspace 6"] = { action = "move-window-to-workspace-6", title = "Move window to workspace 6" },
    ["Move window to workspace 7"] = { action = "move-window-to-workspace-7", title = "Move window to workspace 7" },
    ["Move window to workspace 8"] = { action = "move-window-to-workspace-8", title = "Move window to workspace 8" },
    ["Move window to workspace 9"] = { action = "move-window-to-workspace-9", title = "Move window to workspace 9" },
    ["Move window silently to workspace 10"] = { action = "move-window-silently-to-workspace-10", title = "Move window silently to workspace 10" },
    ["Move window silently to workspace 1"] = { action = "move-window-silently-to-workspace-1", title = "Move window silently to workspace 1" },
    ["Move window silently to workspace 2"] = { action = "move-window-silently-to-workspace-2", title = "Move window silently to workspace 2" },
    ["Move window silently to workspace 3"] = { action = "move-window-silently-to-workspace-3", title = "Move window silently to workspace 3" },
    ["Move window silently to workspace 4"] = { action = "move-window-silently-to-workspace-4", title = "Move window silently to workspace 4" },
    ["Move window silently to workspace 5"] = { action = "move-window-silently-to-workspace-5", title = "Move window silently to workspace 5" },
    ["Move window silently to workspace 6"] = { action = "move-window-silently-to-workspace-6", title = "Move window silently to workspace 6" },
    ["Move window silently to workspace 7"] = { action = "move-window-silently-to-workspace-7", title = "Move window silently to workspace 7" },
    ["Move window silently to workspace 8"] = { action = "move-window-silently-to-workspace-8", title = "Move window silently to workspace 8" },
    ["Move window silently to workspace 9"] = { action = "move-window-silently-to-workspace-9", title = "Move window silently to workspace 9" },
    ["Swap window down"] = { action = "swap-window-down", title = "Swap window down" },
    ["Swap window to the left"] = { action = "swap-window-to-the-left", title = "Swap window to the left" },
    ["Swap window to the right"] = { action = "swap-window-to-the-right", title = "Swap window to the right" },
    ["Swap window up"] = { action = "swap-window-up", title = "Swap window up" },
    ["Focus on next window"] = { action = "focus-on-next-window", title = "Focus on next window" },
    ["Focus on next monitor"] = { action = "focus-on-next-monitor", title = "Focus on next monitor" },
    ["Focus on previous window"] = { action = "focus-on-previous-window", title = "Focus on previous window" },
    ["Focus on previous monitor"] = { action = "focus-on-previous-monitor", title = "Focus on previous monitor" },
    ["Focus on below window"] = { action = "focus-on-below-window", title = "Focus on below window" },
    ["Focus on left window"] = { action = "focus-on-left-window", title = "Focus on left window" },
    ["Focus on right window"] = { action = "focus-on-right-window", title = "Focus on right window" },
    ["Focus on above window"] = { action = "focus-on-above-window", title = "Focus on above window" },
    ["Move window"] = { action = "move-window", title = "Move window" },
    ["Resize window"] = { action = "resize-window", title = "Resize window" },
    ["Expand window left a little"] = { action = "expand-window-left-a-little", title = "Expand window left a little" },
    ["Expand window left a lot"] = { action = "expand-window-left-a-lot", title = "Expand window left a lot" },
    ["Expand window left"] = { action = "expand-window-left", title = "Expand window left" },
    ["Expand window down a little"] = { action = "expand-window-down-a-little", title = "Expand window down a little" },
    ["Expand window down a lot"] = { action = "expand-window-down-a-lot", title = "Expand window down a lot" },
    ["Expand window down"] = { action = "expand-window-down", title = "Expand window down" },
    ["Shrink window left a little"] = { action = "shrink-window-left-a-little", title = "Shrink window left a little" },
    ["Shrink window left a lot"] = { action = "shrink-window-left-a-lot", title = "Shrink window left a lot" },
    ["Shrink window left"] = { action = "shrink-window-left", title = "Shrink window left" },
    ["Shrink window up a little"] = { action = "shrink-window-up-a-little", title = "Shrink window up a little" },
    ["Shrink window up a lot"] = { action = "shrink-window-up-a-lot", title = "Shrink window up a lot" },
    ["Shrink window up"] = { action = "shrink-window-up", title = "Shrink window up" },
    ["Move window to scratchpad"] = { action = "move-window-to-scratchpad", title = "Move window to scratchpad" },
    ["Toggle scratchpad"] = { action = "toggle-scratchpad", title = "Toggle scratchpad" },
    ["Invoke last notification"] = { action = "invoke-last-notification", title = "Invoke last notification" },
    ["Dismiss last notification"] = { action = "dismiss-last-notification", title = "Dismiss last notification" },
    ["Open notification history"] = { action = "open-notification-history", title = "Open notification history" },
    ["Dismiss all notifications"] = { action = "dismiss-all-notifications", title = "Dismiss all notifications" },
    ["Toggle window transparency"] = { action = "toggle-window-transparency", title = "Toggle window transparency" },
    ["Start dictation (push-to-talk)"] = { action = "start-dictation-push-to-talk", title = "Start dictation (push-to-talk)" },
    ["Stop dictation (push-to-talk)"] = { action = "stop-dictation-push-to-talk", title = "Stop dictation (push-to-talk)" },
    ["Download Video from Web App"] = { action = "download-video-from-web-app", title = "Download Video from Web App" },
    ["Copy URL from Web App"] = { action = "copy-url-from-web-app", title = "Copy URL from Web App" },
    ["Make webcam overlay smaller"] = { action = "make-webcam-overlay-smaller", title = "Make webcam overlay smaller" },
    ["Make webcam overlay larger"] = { action = "make-webcam-overlay-larger", title = "Make webcam overlay larger" },
    ["Save window width"] = { action = "save-window-width", title = "Save window width" },
    ["Monitor scaling down"] = { action = "monitor-scaling-down", title = "Monitor scaling down" },
    ["Apps menu"] = { action = "apps-menu", title = "Apps menu" },
    ["Bar panel 1"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 2"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 3"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 4"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 5"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 6"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 7"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 8"] = { action = "bar-panels", title = "Bar panels" },
    ["Bar panel 9"] = { action = "bar-panels", title = "Bar panels" },
    ["Audio"] = { action = "audio", title = "Audio" },
    ["Show battery remaining"] = { action = "show-battery-remaining", title = "Show battery remaining" },
    ["Calendar"] = { action = "calendar", title = "Calendar" },
    ["Show time"] = { action = "show-time", title = "Show time" },
    ["Toggle weather"] = { action = "toggle-weather", title = "Toggle weather" },
    ["Reset zoom"] = { action = "reset-zoom", title = "Reset zoom" },
    ["Bluetooth"] = { action = "bluetooth", title = "Bluetooth" },
    ["Capture menu"] = { action = "capture-menu", title = "Capture menu" },
    ["Display"] = { action = "display", title = "Display" },
    ["Tiled full screen"] = { action = "tiled-full-screen", title = "Tiled full screen" },
    ["Hardware menu"] = { action = "hardware-menu", title = "Hardware menu" },
    ["Toggle menu"] = { action = "toggle-menu", title = "Toggle menu" },
    ["Power"] = { action = "power", title = "Power" },
    ["Calculator"] = { action = "calculator", title = "Calculator" },
    ["Share"] = { action = "share", title = "Share" },
    ["Activity"] = { action = "activity", title = "Activity" },
    ["Network"] = { action = "network", title = "Network" },
    ["Toggle dictation"] = { action = "toggle-dictation", title = "Toggle dictation" },
    ["Zoom in"] = { action = "zoom-in", title = "Zoom in" },
    ["Restore window width"] = { action = "restore-window-width", title = "Restore window width" },
    ["Pseudo window"] = { action = "pseudo-window", title = "Pseudo window" },
    ["ChatGPT"] = { action = "chatgpt", title = "ChatGPT" },
    ["Grok"] = { action = "grok", title = "Grok" },
    ["Move workspace to down monitor"] = { action = "move-workspace-to-down-monitor", title = "Move workspace to down monitor" },
    ["New email"] = { action = "new-email", title = "New email" },
    ["WhatsApp"] = { action = "whatsapp", title = "WhatsApp" },
    ["Move workspace to left monitor"] = { action = "move-workspace-to-left-monitor", title = "Move workspace to left monitor" },
    ["Music TUI"] = { action = "music-tui", title = "Music TUI" },
    ["Move workspace to right monitor"] = { action = "move-workspace-to-right-monitor", title = "Move workspace to right monitor" },
    ["Move workspace to up monitor"] = { action = "move-workspace-to-up-monitor", title = "Move workspace to up monitor" },
    ["X Post"] = { action = "x-post", title = "X Post" },
    ["Agent"] = { action = "agent", title = "Agent" },
    ["Google Messages"] = { action = "google-messages", title = "Google Messages" },
    ["Docker"] = { action = "docker", title = "Docker" },
    ["Email"] = { action = "email", title = "Email" },
    ["Signal"] = { action = "signal", title = "Signal" },
    ["Music"] = { action = "music", title = "Music" },
    ["Editor"] = { action = "editor", title = "Editor" },
    ["Obsidian"] = { action = "obsidian", title = "Obsidian" },
    ["Google Photos"] = { action = "google-photos", title = "Google Photos" },
    ["Google Maps"] = { action = "google-maps", title = "Google Maps" },
    ["Passwords"] = { action = "passwords", title = "Passwords" },
    ["Visual workspace switcher (reverse)"] = { action = "visual-workspace-switcher-reverse", title = "Visual workspace switcher (reverse)" },
    ["Omawrite"] = { action = "omawrite", title = "Omawrite" },
    ["X"] = { action = "x", title = "X" },
    ["YouTube"] = { action = "youtube", title = "YouTube" },
    ["Monitor scaling up"] = { action = "monitor-scaling-up", title = "Monitor scaling up" },
    ["Visual workspace switcher"] = { action = "visual-workspace-switcher", title = "Visual workspace switcher" },
    ["Switch to group window 1"] = { action = "switch-to-group-window-1", title = "Switch to group window 1" },
    ["Switch to group window 2"] = { action = "switch-to-group-window-2", title = "Switch to group window 2" },
    ["Switch to group window 3"] = { action = "switch-to-group-window-3", title = "Switch to group window 3" },
    ["Switch to group window 4"] = { action = "switch-to-group-window-4", title = "Switch to group window 4" },
    ["Switch to group window 5"] = { action = "switch-to-group-window-5", title = "Switch to group window 5" },
    ["Move window to group on bottom"] = { action = "move-window-to-group-on-bottom", title = "Move window to group on bottom" },
    ["Move active window out of group"] = { action = "move-active-window-out-of-group", title = "Move active window out of group" },
    ["Move window to group on left"] = { action = "move-window-to-group-on-left", title = "Move window to group on left" },
    ["Next window in group"] = { action = "binding-32a1ee54ca14", title = "Next window in group" },
    ["Previous window in group"] = { action = "binding-c0193af3a139", title = "Previous window in group" },
    ["Move window to group on right"] = { action = "move-window-to-group-on-right", title = "Move window to group on right" },
    ["Move window to group on top"] = { action = "move-window-to-group-on-top", title = "Move window to group on top" },
    ["Move grouped window focus left"] = { action = "binding-c0193af3a139", title = "Previous window in group" },
    ["Move grouped window focus right"] = { action = "binding-32a1ee54ca14", title = "Next window in group" },
    ["Toggle window grouping"] = { action = "toggle-window-grouping", title = "Toggle window grouping" },
    ["Scroll active workspace forward"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Scroll active workspace backward"] = { action = "workspace-switching", title = "Workspace switching" },
    ["Reveal active window on top"] = { action = "reveal-active-window-on-top", title = "Reveal active window on top" },
    ["Volume down precise"] = { action = "volume-down-precise", title = "Volume down precise" },
    ["Next track"] = { action = "next-track", title = "Next track" },
    ["Volume up precise"] = { action = "volume-up-precise", title = "Volume up precise" },
    ["Brightness down precise"] = { action = "brightness-down-precise", title = "Brightness down precise" },
    ["Brightness up precise"] = { action = "brightness-up-precise", title = "Brightness up precise" },
    ["Previous track"] = { action = "previous-track", title = "Previous track" },
    ["Switch audio output"] = { action = "switch-audio-output", title = "Switch audio output" },
    ["Switch media source"] = { action = "switch-media-source", title = "Switch media source" },
    ["Brightness minimum"] = { action = "brightness-minimum", title = "Brightness minimum" },
    ["Brightness maximum"] = { action = "brightness-maximum", title = "Brightness maximum" },
    ["Volume down"] = { action = "volume-down", title = "Volume down" },
    ["Mute microphone"] = { action = "mute-microphone", title = "Mute microphone" },
    ["Mute"] = { action = "mute", title = "Mute" },
    ["Pause"] = { action = "binding-476f283d3f11", title = "Pause" },
    ["Play"] = { action = "binding-476f283d3f11", title = "Pause" },
    ["Volume up"] = { action = "volume-up", title = "Volume up" },
    ["Eject media"] = { action = "eject-media", title = "Eject media" },
    ["Keyboard brightness down"] = { action = "keyboard-brightness-down", title = "Keyboard brightness down" },
    ["Keyboard brightness up"] = { action = "keyboard-brightness-up", title = "Keyboard brightness up" },
    ["Keyboard backlight cycle"] = { action = "keyboard-backlight-cycle", title = "Keyboard backlight cycle" },
    ["Brightness down"] = { action = "brightness-down", title = "Brightness down" },
    ["Brightness up"] = { action = "brightness-up", title = "Brightness up" },
    ["Power menu"] = { action = "binding-711ecd0805fd", title = "System menu" },
    ["Disable touchpad"] = { action = "disable-touchpad", title = "Disable touchpad" },
    ["Enable touchpad"] = { action = "enable-touchpad", title = "Enable touchpad" },
  }
  local function slug(value)
    return tostring(value):lower():gsub("[^%w]+", "-"):gsub("^-", ""):gsub("-$", "")
  end
  local function quote(value)
    return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
  end
  local function coaching_identity(description)
    local text = tostring(description or "")
    local known = coaching_by_description[text]
    if known then return known.action, known.title end
    if text:match("^Switch to workspace %d+$") or text == "Next workspace"
      or text == "Previous workspace" or text == "Former workspace"
      or text == "Scroll active workspace forward"
      or text == "Scroll active workspace backward" then
      return "workspace-switching", "Workspace switching"
    end
    if text:match("^Bar panel %d+$") then
      return "bar-panels", "Bar panels"
    end
    return slug(text), text
  end
  function hl.bind(keys, dispatcher, options)
    local original = _G.omarchy_sensei_original_hl_bind
    local description = options and (options.description or options.desc)
    local key_text = tostring(keys or "")
    local source_scan = type(dispatcher) == "table" and dispatcher.__omarchy_dispatcher
    if source_scan or not description or key_text:find("mouse", 1, true) or key_text:find("switch:", 1, true) then
      return original(keys, dispatcher, options)
    end
    local action, title = coaching_identity(description)
    local command = "omarchy-sensei complete --action " .. quote(action)
      .. " --title " .. quote(title)
    return original(keys, function()
      hl.dispatch(dispatcher)
      hl.exec_cmd(command)
    end, options)
  end

  -- Observe only completed left clicks that coincide with a real active-window
  -- transition. The binding is non-consuming: Hyprland still delivers the
  -- original click unchanged, and ordinary clicks launch no process.
  if hl.on and hl.timer and hl.get_active_window then
    local last_active = ""
    local pointer_down = nil
    local recent_focus = nil
    local pointer_serial = 0
    local function window_address(window)
      if not window or not window.address then return "" end
      return tostring(window.address)
    end
    local ok, active = pcall(hl.get_active_window)
    if ok then last_active = window_address(active) end
    hl.bind("mouse:272", function()
      pointer_serial = pointer_serial + 1
      local serial = pointer_serial
      pointer_down = { serial = serial }
      recent_focus = nil
      hl.timer(function()
        if pointer_down and pointer_down.serial == serial then pointer_down = nil end
        if recent_focus and recent_focus.serial == serial then recent_focus = nil end
      end, { timeout = 800, type = "oneshot" })
    end, { non_consuming = true })
    hl.on("window.active", function(window)
      local next_active = window_address(window)
      if pointer_down and last_active ~= "" and next_active ~= "" and next_active ~= last_active then
        recent_focus = { from = last_active, to = next_active, serial = pointer_down.serial }
      end
      last_active = next_active
    end)
    hl.bind("mouse:272", function()
      local transition = recent_focus
      pointer_down = nil
      recent_focus = nil
      if transition then
        hl.exec_cmd("omarchy-sensei coach-focus --from " .. quote(transition.from)
          .. " --to " .. quote(transition.to))
      end
    end, { release = true, non_consuming = true })
  end
end
