accent = "#85abbc"
cursor = "#dcd6d6"
foreground = "#dcd6d6"
background = "#232829"
selection_foreground = "#dcd6d6"
selection_background = "#85abbc"

color0 = "#232829"
color1 = "#b39a98"
color2 = "#98b3a3"
color3 = "#93b3a6"
color4 = "#85abbc"
color5 = "#bea7b0"
color6 = "#98b3b3"
color7 = "#d6dcdb"
color8 = "#788587"
color9 = "#b39898"
color10 = "#98b3a3"
color11 = "#c8dad3"
color12 = "#89b1c3"
color13 = "#e5dbdf"
color14 = "#98b3b3"
color15 = "#dcd6d6"
