-- Generated by hypr2lua-web.

hl.config({
  general = {
    col = {
      active_border = "rgb(85abbc)",
      inactive_border = "rgb(4a5a5d)",
    },
    border_size = 2,
    gaps_in = 2,
    gaps_out = 4,
  },
  animations = {
    enabled = true,
  },
  decoration = {
    rounding = 14,
    shadow = {
      enabled = false,
      range = 15,
      render_power = 5,
      offset = "0 0",
    },
    blur = {
      enabled = true,
      size = 5,
      passes = 3,
      contrast = 1.02,
      brightness = 1.00,
      vibrancy = 0.12,
      vibrancy_darkness = 0.15,
      noise = 0.02,
      ignore_opacity = true,
      new_optimizations = true,
    },
    active_opacity = 0.90,
    inactive_opacity = 0.88,
    fullscreen_opacity = 1.0,
  },
})

hl.curve("easeSoft", { type = "bezier", points = { { 0.22, 0.61 }, { 0.36, 1 } } })
hl.curve("easePop", { type = "bezier", points = { { 0.26, 0.70 }, { 0.48, 1 } } })
hl.curve("easeFade", { type = "bezier", points = { { 0.33, 0.00 }, { 0.20, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3.0,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 2.8,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2.6,
  bezier = "easeFade",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3.2,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 2.4,
  bezier = "easeFade",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 2.2,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 2.0,
  bezier = "easeFade",
})
hl.animation({
  leaf = "fadeDim",
  enabled = true,
  speed = 2.0,
  bezier = "easeFade",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 2.4,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 2.2,
  bezier = "easePop",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 2.0,
  bezier = "easeFade",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 2.6,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "specialWorkspace",
  enabled = true,
  speed = 2.4,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 3.4,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 3.8,
  bezier = "easeSoft",
})
hl.animation({
  leaf = "fadeSwitch",
  enabled = true,
  speed = 1.8,
  bezier = "easeFade",
})
