{
  "manifest_version": 2,
  "name": "Omarchy Brave Theme",
  "version": "1.0.0",
  "description": "Chromium theme extension for Omarchy dynamic system theme. Generated by omarchy-sync-brave — do not hand-edit. The companion MV3 extension (brave-polish) handles NTP and site polish.",
  "theme": {
    "colors": {
      "frame": [{{ background_rgb }}],
      "frame_inactive": [{{ background_rgb }}],
      "toolbar": [{{ background_rgb }}],
      "tab_text": [{{ foreground_rgb }}],
      "tab_background_text": [{{ muted_rgb }}],
      "bookmark_text": [{{ foreground_rgb }}],
      "ntp_background": [{{ background_rgb }}],
      "ntp_text": [{{ foreground_rgb }}],
      "ntp_link": [{{ accent_rgb }}],
      "ntp_header": [{{ background_rgb }}],
      "button_background": [{{ background_rgb }}]
    },
    "tints": {
      "buttons": [0.5, 0.5, 0.5]
    },
    "properties": {
      "ntp_logo_alternate": 1
    }
  }
}
