{
  "mode": "{{ mode }}",
  "dark100": "{{ background }}",
  "dark200": "{{ dark_background }}",
  "dark300": "{{ darker_background }}",
  "dark400": "{{ selection }}",
  "dark500": "{{ muted }}",
  "dark600": "{{ dark_foreground }}",
  "dark700": "{{ soft_fg }}",
  "dark800": "{{ foreground }}",
  "dark900": "{{ bright_foreground }}",
  "dark1000": "{{ bright_foreground }}",
  "darkPrimary": "{{ accent }}",
  "darkSecondary": "{{ green }}",
  "darkAmber": "{{ yellow }}",
  "darkDanger": "{{ red }}",

  "light100": "{{ foreground }}",
  "light200": "{{ foreground }}",
  "light300": "{{ dark_foreground }}",
  "light400": "{{ muted }}",
  "light500": "{{ muted }}",
  "light600": "{{ selection }}",
  "light700": "{{ lighter_background }}",
  "light800": "{{ background }}",
  "light900": "{{ background }}",
  "light1000": "{{ background }}",
  "lightPrimary": "{{ accent }}",
  "lightSecondary": "{{ green }}",
  "lightAmber": "{{ yellow }}",
  "lightDanger": "{{ red }}"
}
