[DetailsPanel]
DirReadErrColor=#ff0000

[DirectoryTree]
CrossFilesystems=false
IgnoreHardLinks=false
SlowUpdateMillisec=3000
TreeIconDir=:/icons/tree-medium/
UpdateTimerMillisec=333
UseBoldForDominant=true

[MainWindow]
Layout=L2
ShowTreemap=true
StatusBarTimeoutMillisec=3000
UrlInWindowTitle=false
UseTreemapHover=false
VerboseSelection=false
WindowPos=@Point(0 0)
WindowSize=@Size(1268 756)

[MainWindow-Subwindows]
MainSplitter=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\xac\0\0\0\xc0\x1\0\0\0\x4\x1\0\0\0\x2\0)
TopSplitter="@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x1,\x1\0\0\0\x4\x1\0\0\0\x1\0)"

[OpenDirDialog]
MainSplitter=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x1\t\0\0\0\0\b\x1\0\0\0\x1\0)
WindowPos=@Point(0 0)
WindowSize=@Size(640 420)

[PercentBar]
Background=#23372b
Colors=#509475, #38bdf8, #818cf8, #a78bfa, #f472b6, #fb923c, #34d399, #22d3ee, #fbbf24, #f87171, #c084fc, #60a5fa
PercentBarColumnWidth=180

[Pkg]
GetRpmPkgListWarningSec=7

[TreeTheme-dark]
DirReadErrColor=#f87171
SubtreeReadErrColor=#fbbf24

[TreeViewColumns]
Width_GroupCol=auto
Width_LatestMTimeCol=auto
Width_NameCol=auto
Width_OctalPermissionsCol=auto
Width_OldestFileMTimeCol=auto
Width_PercentBarCol=auto
Width_PercentNumCol=auto
Width_PermissionsCol=auto
Width_SizeCol=auto
Width_TotalFilesCol=auto
Width_TotalItemsCol=auto
Width_TotalSubDirsCol=auto
Width_UserCol=auto

[TreeViewLayout_L1]
Columns=NameCol, PercentBarCol, PercentNumCol, SizeCol, LatestMTimeCol
ShowDetailsPanel=true

[TreeViewLayout_L2]
Columns=NameCol, PercentBarCol, PercentNumCol, SizeCol, TotalItemsCol, TotalFilesCol, TotalSubDirsCol, LatestMTimeCol
ShowDetailsPanel=true

[TreeViewLayout_L3]
Columns=NameCol, PercentBarCol, PercentNumCol, SizeCol, TotalItemsCol, TotalFilesCol, TotalSubDirsCol, LatestMTimeCol, OldestFileMTimeCol, UserCol, GroupCol, PermissionsCol, OctalPermissionsCol
ShowDetailsPanel=false

[Treemaps]
AmbientLight=75
CurrentItemColor=#f87171
CushionGridColor=#273a32
CushionShading=true
DirFillColor=#1c2d27
DirGradientEnd=#263d33
DirGradientStart=#182721
EnforceContrast=false
FileFillColor=#509475
ForceCushionGrid=false
MinTileSize=3
OutlineColor=#111c18
SelectedItemsColor=#50e3a5
Squarify=true
UseDirGradient=true
