.pragma library
// Generated by bin/build-renderer from the qrgen app - do not edit.
// Rebuild with: bin/build-renderer [path-to-qrgen-checkout]
// Bundles qrgen and lean-qr, both MIT - see LICENSE and THIRD-PARTY.md.

// QML's engine is not a browser, and lean-qr expects two things from one.
//
// TextEncoder it uses to measure and emit UTF-8, which matters here: an emoji
// payload is UTF-8 bytes, so this has to be right rather than approximate.
//
// TextDecoder it uses only to build the Shift-JIS lookup that decides whether
// kanji mode would make a smaller code. That table is 7973 entries of encoding
// data, which is not worth carrying in a bar widget, so this stub declines the
// question: Japanese text still encodes, as UTF-8, in a slightly larger code.
var TextEncoder = function () {};
TextEncoder.prototype.encode = function (input) {
  var text = String(input);
  var bytes = [];
  for (var i = 0; i < text.length; i++) {
    var point = text.codePointAt(i);
    if (point > 0xFFFF) i++; // the pair is one code point
    if (point < 0x80) {
      bytes.push(point);
    } else if (point < 0x800) {
      bytes.push(0xC0 | (point >> 6), 0x80 | (point & 63));
    } else if (point < 0x10000) {
      bytes.push(0xE0 | (point >> 12), 0x80 | ((point >> 6) & 63), 0x80 | (point & 63));
    } else {
      bytes.push(0xF0 | (point >> 18), 0x80 | ((point >> 12) & 63),
                 0x80 | ((point >> 6) & 63), 0x80 | (point & 63));
    }
  }
  return new Uint8Array(bytes);
};

var TextDecoder = function () {};
TextDecoder.prototype.decode = function () { return "\uFFFD"; };
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
var ye = [0.2, 0.375, 0.5555555555555556, 0.6666666666666666], we = (e, r) => (t) => { let n = 4 * e + t - 4, o = "*-04-39?2$%%$%%'$%''%'''%')(%'))%(++'(++'(+.'+-.',/3',33)-/5)-43).36)058*18<+37<+4:<,4:E,5<A-7>C/8@F/:EH/<EK0=FM1?IP2@KS3BNV4DPY5FS\\6HV_6IXb7K[e8N^i9Pam;Rdp<Tgt".charCodeAt(n) - 35, i = n > 8 ? o : 1, s = r / i | 0, a = r % i, l = i - a, c = n > 8 ? s * ye[t] + (e > 5) & -2 : o, u = s - c; return { t: l * u + a * u + a, o: [[l, u], [a, u + 1]], i: c }; }, Z = { min: 0, L: 0, M: 1, Q: 2, H: 3, max: 3 }, B = (e) => new Uint8Array(e), I = (e) => { let r = Error(`lean-qr error ${e}`); throw r.code = e, r; }, V = (e) => "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:".indexOf(e), j = (e) => e.charCodeAt(0), le = (...e) => (r, t) => e.forEach((n) => n(r, t)), ue = (e) => (r) => { r.eci !== e && (r.push(7, 4), e < 128 ? r.push(e, 8) : e < 16384 ? r.push(32768 | e, 16) : r.push(12582912 | e, 24), r.eci = e); }, X = (e) => (r, t) => { r.push(4, 4), r.push(e.length, 8 + 8 * (t > 9)), e.forEach((n) => r.push(n, 8)); }, O = (e, r, t, n, o = (s, a) => t(s.length, a), i = n ? (s) => le(ue(n), e(s)) : e) => (i.test = r, i.l = t, i.est = o, i.eci = n && [n], i), ce = O((e) => (r, t) => { r.push(1, 4), r.push(e.length, 10 + 2 * (t > 26) + 2 * (t > 9)); let n = 0; for (; n < e.length - 2; n += 3)
    r.push(+e.slice(n, n + 3), 10); n < e.length - 1 ? r.push(+e.slice(n), 7) : n < e.length && r.push(+e[n], 4); }, (e) => /[0-9]/.test(e), (e, r) => 14 + 2 * (r > 26) + 2 * (r > 9) + 10 * e / 3), me = O((e) => (r, t) => { r.push(2, 4), r.push(e.length, 9 + 2 * (t > 26) + 2 * (t > 9)); let n = 0; for (; n < e.length - 1; n += 2)
    r.push(45 * V(e[n]) + V(e[n + 1]), 11); n < e.length && r.push(V(e[n]), 6); }, (e) => V(e) >= 0, (e, r) => 13 + 2 * (r > 26) + 2 * (r > 9) + 5.5 * e), F = O((e) => X([...e].map(j)), (e) => j(e) < 128, (e, r) => 12 + 8 * (r > 9) + 8 * e);
F._ = !0, F.u = !0;
var G = O(F, (e) => j(e) < 256, F.l, 3);
G._ = !0;
var ae = new TextEncoder, J = O((e) => X(ae.encode(e)), () => 1, 0, 26, (e, r) => 12 + 8 * (r > 9) + 8 * ae.encode(e).length);
J._ = !0;
var U = () => { let e = new Map, r = new TextDecoder("sjis"), t = B(2); for (let n = 0; n < 7973; ++n)
    t[0] = n / 192 + 129 + 64 * (n > 5951), t[1] = n % 192 + 64, e.set(r.decode(t), n); return e.delete("�"), U = () => e, e; }, W = O((e) => (r, t) => { r.push(8, 4), r.push(e.length, 8 + 2 * (t > 26) + 2 * (t > 9)); for (let n of e)
    r.push(U().get(n), 13); }, (e) => U().has(e), (e, r) => 12 + 2 * (r > 26) + 2 * (r > 9) + 13 * e);
W._ = !0;
var be = [ce, me, F, G, W, J], K = { auto: (e, { modes: r = be } = {}) => (t, n) => { var _a; let o = r.map((u, h) => { let p = new Map, y = (d, g) => (p.has(d) || p.set(d, g(d, n)), p.get(d)); return { m: u, h: 1 << h, C: u.est("", n), S: u.l ? (d, g) => y(g - d, u.l) : (d, g) => y(e.slice(d, g), u.est) }; }), i = [{ v: 0 }], s = 0, a = 0, l = -1; for (let u of [...e, ""]) {
        let h = 0;
        if (u)
            for (let p of o)
                p.m.test(u) && (h |= p.h);
        if (!u || h !== l) {
            if (l !== -1) {
                let p = new Set(i.map((d) => d.D)), y = [];
                for (let { m: d, C: g, S: w, h: x } of o)
                    if (l & x) {
                        let m = w(s, a);
                        for (let b of (_a = d.eci) !== null && _a !== void 0 ? _a : p)
                            if (!d.u || !b) {
                                let v;
                                for (let S of i)
                                    if (S.D === b || d.eci) {
                                        let M = S.m === d && S.D === b, Q = M ? S.V : S, se = d._ && M ? S.v + m - g : Q.v + 12 * (Q.D !== b) + (M ? w(M ? S.$ : s, a) : m);
                                        (!v || se < v.v) && (v = { $: M ? S.$ : s, V: Q, m: d, D: b, A: a, v: se });
                                    }
                                v && y.push(v);
                            }
                    }
                i = y;
            }
            l = h, s = a;
        }
        a += u.length;
    } i.length || I(5); let c = []; for (let u = i.reduce((h, p) => p.v < h.v ? p : h); u.m; u = u.V)
        c.push(u.m(e.slice(u.$, u.A))); c.reverse().forEach((u) => u(t, n)); }, multi: le, eci: ue, bytes: X, numeric: ce, alphaNumeric: me, ascii: F, iso8859_1: G, shift_jis: W, utf8: J }, $e = () => ({ F: B(2956), I: 0, push(e, r) { for (let t = r, n = 8 - (7 & this.I); t > 0; t -= n, n = 8)
        this.F[this.I >> 3] |= e << n >> t, this.I += t < n ? t : n; } }), P = (e, r = e * e, t = B(r)) => ({ size: e, K: t, get: (n, o) => n >= 0 && n < e && !!(1 & t[o * e + n]), toString({ on: n = "##", off: o = "  ", lf: i = `
`, pad: s = 4, padX: a = s, padY: l = s } = {}) { let c = ""; for (let u = -l; u < e + l; ++u) {
        for (let h = -a; h < e + a; ++h)
            c += this.get(h, u) ? n : o;
        c += i;
    } return c; }, toImageData(n, { on: o = [0, 0, 0], off: i = [0, 0, 0, 0], pad: s = 4, padX: a = s, padY: l = s } = {}) { let c = e + 2 * a, u = e + 2 * l, h = n.createImageData(c, u), p = new Uint32Array(h.data.buffer); h.data.set([...o, 255]); let y = p[0]; h.data.set([...i, 255]); let d = p[0]; for (let g = 0; g < u; ++g)
        for (let w = 0; w < c; ++w)
            p[g * c + w] = this.get(w - a, g - l) ? y : d; return h; }, toCanvas(n, o) { let i = n.getContext("2d"), s = this.toImageData(i, o); n.width = s.width, n.height = s.height, i.putImageData(s, 0, 0); }, toDataURL(_a = {}) { var { type: n = "image/png", scale: o = 1 } = _a, i = __rest(_a, ["type", "scale"]); let s = document.createElement("canvas"), a = s.getContext("2d"), l = this.toImageData(a, i); return s.width = l.width * o, s.height = l.height * o, a.putImageData(l, 0, 0), a.imageSmoothingEnabled = !1, a.globalCompositeOperation = "copy", a.drawImage(s, 0, 0, l.width, l.height, 0, 0, s.width, s.height), s.toDataURL(n, 1); } }), H = [(e, r) => 1 & (e ^ r), (e, r) => 1 & r, (e) => e % 3, (e, r) => (e + r) % 3, (e, r) => 1 & (e / 3 ^ r >> 1), (e, r) => (e & r & 1) + e * r % 3, (e, r) => (e & r) + e * r % 3 & 1, (e, r) => (e ^ r) + e * r % 3 & 1], q = B(511);
for (let e = 0, r = 1; e < 255; r = 2 * r ^ 285 * (r > 127))
    q[q[r + 255] = e++] = r;
var pe = (e) => q[e % 255], de = (e) => q[e + 255], Se = (e, r) => { let t = B(e.length + r.length - 1); for (let n = 0; n < e.length; ++n)
    for (let o = 0; o < r.length; ++o)
        t[n + o] ^= pe(e[n] + r[o]); return t.map(de); }, xe = (e, r) => { let t = B(e.length + r.length - 1); t.set(e, 0); for (let n = 0; n < e.length; ++n)
    if (t[n]) {
        let o = de(t[n]);
        for (let i = 0; i < r.length; ++i)
            t[n + i] ^= pe(r[i] + o);
    } return t.slice(e.length); }, Y = [[0], [0, 0]];
for (let e = 1; e < 30; ++e)
    Y.push(Se(Y[e], [0, e]));
var ve = (e, r) => { let t = [[], []], n = 0, o = 0; for (let [s, a] of r.o)
    for (let l = 0; l < s; ++l, n += a) {
        let c = e.slice(n, n + a);
        t[0].push(c), t[1].push(xe(c, Y[r.i])), o += a + r.i;
    } let i = B(o); o = 0; for (let s of t)
    for (let a = 0, l = -1; l < o; ++a) {
        l = o;
        for (let c of s)
            a < c.length && (i[o++] = c[a]);
    } return i; }, fe = (e, r, t) => { let n = e <<= t; for (let o = 134217728; o >>= 1;)
    n & o && (n ^= r * (o >> t)); return n | e; }, Ce = ({ size: e, K: r }, t) => { let n = (s, a, l, c) => { for (; l-- > 0; s += e)
    r.fill(c, s, s + a); }, o = (s, a, l) => { for (let c = 0; c++ < 3; l -= 2)
    n(a * e + s - (l >> 1) * (e + 1), l, l, 2 | c); }, i = 2 * ((e - 13) / (1 + (t / 7 | 0)) / 2 + 0.75 | 0); if (t > 1)
    for (let s = e - 7; s > 8; s -= i) {
        for (let a = s; a > 8; a -= i)
            o(s, a, 5);
        s < e - 7 && o(s, 6, 5);
    } if (t > 6)
    for (let s = fe(t, 7973, 12), a = 1; a < 7; ++a)
        for (let l = 12; l-- > 9; s >>= 1)
            r[a * e - l] = 2 | 1 & s; n(7, 2, 9, 2), n(e - 8, 8, 9, 2); for (let s = 0; s < e; ++s)
    r[6 * e + s] = 3 ^ 1 & s; o(3, 3, 7), o(e - 4, 3, 7); for (let s = 0; s < e; ++s)
    for (let a = s; a < e; ++a)
        r[a * e + s] = r[s * e + a]; r[(e - 8) * e + 8] = 3; }, Ee = ({ size: e, K: r }) => { let t = []; for (let n = e - 2, o = e, i = -1; n >= 0; n -= 2) {
    for (n === 5 && (n = 4); o += i, o !== -1 && o !== e;) {
        let s = o * e + n;
        r[s + 1] || t.push(s + 1), r[s] || t.push(s);
    }
    i *= -1;
} return t; }, ze = ({ K: e }, r, t) => r.forEach((n, o) => e[n] = t[o >> 3] >> (7 & ~o) & 1), Me = ({ size: e, K: r }, t, n, o) => { for (let s = 0; s < e; ++s)
    for (let a = 0; a < e; ++a) {
        let l = s * e + a;
        r[l] ^= !(t(a, s) || 2 & r[l]);
    } let i = 21522 ^ fe((1 ^ o) << 3 | n, 1335, 10); for (let s = 0; s++ < 8; i >>= 1)
    r[(s - (s < 7)) * e + 8] = 1 & i, r[9 * e - s] = 1 & i; for (let s = 8; --s, i; i >>= 1)
    r[8 * e + s - (s < 7)] = 1 & i, r[(e - s) * e + 8] = 1 & i; }, Le = ({ size: e, K: r }, t = 0, n = 0) => { for (let o = 0; o < e; ++o) {
    for (let i = 0; i < 2; ++i)
        for (let s, a = 0, l = 0, c = 2; a < e; ++a) {
            let u = 1 & r[i ? o * e + a : a * e + o];
            n += u, l = (l >> 1 | 2098176) & (3047517 ^ u - 1), 2049 & l && (t += 40), u ^ c && (s = 0), c = u, t += ++s === 5 ? 3 : s > 5;
        }
    if (o)
        for (let i = e + o, s = 5 * r[o - 1] ^ r[o]; i < e * e; i += e) {
            let a = 5 * r[i - 1] ^ r[i];
            t += 3 * !(1 & (s | a) | 4 & (s ^ a)), s = a;
        }
} return t + 10 * (10 * Math.abs(n / (e * e) - 1) | 0); }, ie = [], N = (e = I(1), _a = {}) => { var { minCorrectionLevel: r = 0, maxCorrectionLevel: t = 3, minVersion: n = 1, maxVersion: o = 40, mask: i, trailer: s = 60433 } = _a, a = __rest(_a, ["minCorrectionLevel", "maxCorrectionLevel", "minVersion", "maxVersion", "mask", "trailer"]); t < r && I(3), o < n && I(2), typeof e == "string" && (e = K.auto(e, a)); for (let l = n, c = 0; l <= o; ++l) {
    let u = ie[l];
    u || (ie[l] = u = P(4 * l + 17), Ce(u, l), u.p = Ee(u));
    let h = we(l, u.p.length >> 3);
    if (8 * h(r).t < c)
        continue;
    let p = $e();
    e(p, l), c = p.I;
    for (let y = t; y >= r; --y) {
        let d = h(y);
        if (8 * d.t < c)
            continue;
        for (p.I = c + 11 & -8; p.I < 8 * d.t;)
            p.push(s, 16);
        let g = P(u.size, u.K);
        return ze(g, u.p, ve(p.F, d)), (H[i !== null && i !== void 0 ? i : -1] ? [H[i]] : H).map((w, x) => { let m = P(g.size, g.K); return Me(m, w, i !== null && i !== void 0 ? i : x, y), m.s = Le(m), m; }).reduce((w, x) => x.s < w.s ? x : w);
    }
} I(4); };
N.with = (...e) => (r, t) => N(r, Object.assign({ modes: [...be, ...e] }, t));
var Be = ["L", "M", "Q", "H"], k = 7;
function ee(e, r = {}) { let t = r.correction && Be.includes(r.correction) ? r.correction : "M", n = r.alphanumeric ? K.alphaNumeric(e) : K.auto(e), o = N(n, { minVersion: 1, maxVersion: 40, minCorrectionLevel: Z[t], maxCorrectionLevel: Z.H }), i = o.size, s = [{ x: 0, y: 0 }, { x: i - k, y: 0 }, { x: 0, y: i - k }]; return { size: i, version: (i - 17) / 4, finderSize: k, finders: s, get: (a, l) => o.get(a, l), isFinder: (a, l) => s.some((c) => a >= c.x && a < c.x + k && l >= c.y && l < c.y + k) }; }
var f = (e) => Math.round(e * 1000) / 1000;
function E(e, r, t, n, o = {}) { let { tl: i = 0, tr: s = 0, br: a = 0, bl: l = 0 } = o, c = (h, p, y) => `A${f(h)},${f(h)} 0 0 1 ${f(p)},${f(y)}`, u = `M${f(e + i)},${f(r)}`; if (u += `H${f(e + t - s)}`, s)
    u += c(s, e + t, r + s); if (u += `V${f(r + n - a)}`, a)
    u += c(a, e + t - a, r + n); if (u += `H${f(e + l)}`, l)
    u += c(l, e, r + n - l); if (u += `V${f(r + i)}`, i)
    u += c(i, e + i, r); return u + "Z"; }
function C(e, r, t, n = 0) { return E(e, r, t, t, { tl: n, tr: n, br: n, bl: n }); }
function re(e, r, t) { return `M${f(e - t)},${f(r)}a${f(t)},${f(t)} 0 1 0 ${f(t * 2)},0a${f(t)},${f(t)} 0 1 0 ${f(-t * 2)},0Z`; }
function he(e, r, t, n = 0) { let o = t / 2, i = o - n; return `M${f(e + o)},${f(r + o - i)}L${f(e + o + i)},${f(r + o)}L${f(e + o)},${f(r + o + i)}L${f(e + o - i)},${f(r + o)}Z`; }
var _ = { square: { label: "Square", draw: (e, r) => C(e, r, 1) }, rounded: { label: "Rounded", draw: (e, r) => C(e, r, 1, 0.35) }, dot: { label: "Dots", draw: (e, r) => re(e + 0.5, r + 0.5, 0.5) }, diamond: { label: "Diamond", draw: (e, r) => he(e, r, 1, -0.1) }, smooth: { label: "Smooth", draw: (e, r, t) => { let n = t(0, -1), o = t(0, 1), i = t(-1, 0), s = t(1, 0); return E(e, r, 1, 1, { tl: !n && !i ? 0.5 : 0, tr: !n && !s ? 0.5 : 0, br: !o && !s ? 0.5 : 0, bl: !o && !i ? 0.5 : 0 }); } }, classy: { label: "Classy", draw: (e, r, t) => { let n = t(0, -1), o = t(0, 1), i = t(-1, 0), s = t(1, 0); return E(e, r, 1, 1, { tl: !n && !i ? 0.5 : 0, br: !o && !s ? 0.5 : 0 }); } }, "bars-v": { label: "Vertical bars", draw: (e, r, t) => E(e + 0.1, r, 0.8, 1, { tl: t(0, -1) ? 0 : 0.35, tr: t(0, -1) ? 0 : 0.35, bl: t(0, 1) ? 0 : 0.35, br: t(0, 1) ? 0 : 0.35 }) }, "bars-h": { label: "Horizontal bars", draw: (e, r, t) => E(e, r + 0.1, 1, 0.8, { tl: t(-1, 0) ? 0 : 0.35, bl: t(-1, 0) ? 0 : 0.35, tr: t(1, 0) ? 0 : 0.35, br: t(1, 0) ? 0 : 0.35 }) } };
function R(e, r, t, n) { return t(e, r, 7) + " " + n(e + 1, r + 1, 5); }
var T = { square: { label: "Square", draw: (e, r) => R(e, r, (t, n, o) => C(t, n, o), (t, n, o) => C(t, n, o)) }, rounded: { label: "Rounded", draw: (e, r) => R(e, r, (t, n, o) => C(t, n, o, 1.75), (t, n, o) => C(t, n, o, 1.05)) }, circle: { label: "Circle", draw: (e, r) => re(e + 3.5, r + 3.5, 3.5) + " " + C(e + 1, r + 1, 5, 1.8) }, leaf: { label: "Leaf", draw: (e, r) => R(e, r, (t, n, o) => E(t, n, o, o, { tl: o * 0.36, br: o * 0.36 }), (t, n, o) => E(t, n, o, o, { tl: o * 0.3, br: o * 0.3 })) }, petal: { label: "Petal", draw: (e, r) => R(e, r, (t, n, o) => E(t, n, o, o, { tr: o * 0.36, bl: o * 0.36 }), (t, n, o) => E(t, n, o, o, { tr: o * 0.3, bl: o * 0.3 })) }, cushion: { label: "Cushion", draw: (e, r) => R(e, r, (t, n, o) => C(t, n, o, 2.4), (t, n, o) => C(t, n, o, 0.6)) } }, A = { square: { label: "Square", draw: (e, r) => C(e + 2, r + 2, 3) }, rounded: { label: "Rounded", draw: (e, r) => C(e + 2, r + 2, 3, 0.9) }, dot: { label: "Dot", draw: (e, r) => re(e + 3.5, r + 3.5, 1.6) }, diamond: { label: "Diamond", draw: (e, r) => he(e + 2, r + 2, 3, -0.2) }, leaf: { label: "Leaf", draw: (e, r) => E(e + 2, r + 2, 3, 3, { tl: 1.3, br: 1.3 }) }, petal: { label: "Petal", draw: (e, r) => E(e + 2, r + 2, 3, 3, { tr: 1.3, bl: 1.3 }) }, cushion: { label: "Cushion", draw: (e, r) => C(e + 2, r + 2, 3, 1.05) } };
var z = { link: "", compress: !1, compressTarget: "short", compressEmoji: !1, correction: "M", margin: 4, shapes: { body: "square", eyeFrame: "square", eyeBall: "square" }, colors: { foreground: "#111827", background: "#ffffff", transparentBackground: !1, eyeFrame: "", eyeBall: "" }, logo: { src: null, name: "", scale: 0.22, padding: 0.6, clear: !0, backdrop: !0, radius: 0.15 } };
var te = (e, r, t) => Math.min(t, Math.max(r, e)), L = (e) => Math.round(e * 1000) / 1000, D = (e) => String(e).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
function ne(e, r, t) { var _a; return (_a = e[r]) !== null && _a !== void 0 ? _a : e[t]; }
function Fe(e, r) { if (!r.src)
    return null; let t = e.size * te(r.scale, 0.05, 0.4), n = (e.size - t) / 2; return { x: n, y: n, side: t, pad: Math.max(0, r.padding || 0) }; }
function ge(e, r = z) { var _a; let t = Object.assign(Object.assign({}, z.shapes), r.shapes), n = Object.assign(Object.assign({}, z.colors), r.colors), o = Object.assign(Object.assign({}, z.logo), r.logo), i = te(Math.round((_a = r.margin) !== null && _a !== void 0 ? _a : 4), 0, 16), s = e.size + i * 2, a = Fe(e, o), l = (m, b) => { if (!a || !o.clear)
    return !1; return m + 1 > a.x - a.pad && m < a.x + a.side + a.pad && b + 1 > a.y - a.pad && b < a.y + a.side + a.pad; }, c = new Uint8Array(e.size * e.size); for (let m = 0; m < e.size; m++)
    for (let b = 0; b < e.size; b++)
        if (e.get(b, m) && !e.isFinder(b, m) && !l(b, m))
            c[m * e.size + b] = 1; let u = (m, b) => m >= 0 && b >= 0 && m < e.size && b < e.size && c[b * e.size + m] === 1, h = ne(_, t.body, "square"), p = ne(T, t.eyeFrame, "square"), y = ne(A, t.eyeBall, "square"), d = ""; for (let m = 0; m < e.size; m++)
    for (let b = 0; b < e.size; b++) {
        if (!u(b, m))
            continue;
        let v = (S, M) => u(b + S, m + M);
        d += h.draw(b + i, m + i, v) + " ";
    } let g = "", w = ""; for (let m of e.finders)
    g += p.draw(m.x + i, m.y + i) + " ", w += y.draw(m.x + i, m.y + i) + " "; let x = []; if (!n.transparentBackground)
    x.push(`<rect width="${s}" height="${s}" fill="${D(n.background)}"/>`); if (x.push(`<path d="${d.trim()}" fill="${D(n.foreground)}"/>`), x.push(`<path d="${g.trim()}" fill="${D(n.eyeFrame || n.foreground)}" fill-rule="evenodd"/>`), x.push(`<path d="${w.trim()}" fill="${D(n.eyeBall || n.foreground)}"/>`), a) {
    let m = L(a.x + i), b = L(a.y + i), v = L(a.side);
    if (o.backdrop && !n.transparentBackground) {
        let S = a.pad, M = L(v * te(o.radius, 0, 0.5));
        x.push(`<rect x="${L(m - S)}" y="${L(b - S)}" width="${L(v + S * 2)}" height="${L(v + S * 2)}" rx="${M}" ry="${M}" fill="${D(n.background)}"/>`);
    }
    x.push(`<image href="${D(o.src)}" x="${m}" y="${b}" width="${v}" height="${v}" preserveAspectRatio="xMidYMid meet"/>`);
} return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${s} ${s}" width="${s * 8}" height="${s * 8}" shape-rendering="geometricPrecision">${x.join("")}</svg>`; }
var oe = (e) => Object.entries(e).map(([r, t]) => ({ value: r, label: t.label }));
function Qe() { return { body: oe(_), eyeFrame: oe(T), eyeBall: oe(A), defaults: z }; }
function Pe(e, r, t) { var _a, _b, _c; try {
    if (!e)
        return { ok: !1, error: "Nothing to encode" };
    let n = Object.assign(Object.assign(Object.assign({}, z), r), { shapes: Object.assign(Object.assign({}, z.shapes), (_a = r === null || r === void 0 ? void 0 : r.shapes) !== null && _a !== void 0 ? _a : {}), colors: Object.assign(Object.assign({}, z.colors), (_b = r === null || r === void 0 ? void 0 : r.colors) !== null && _b !== void 0 ? _b : {}), logo: Object.assign(Object.assign({}, z.logo), (_c = r === null || r === void 0 ? void 0 : r.logo) !== null && _c !== void 0 ? _c : {}) }), o = ee(e, { correction: n.correction, alphanumeric: !!t });
    return { ok: !0, svg: ge(o, n), size: o.size, version: o.version };
}
catch (n) {
    return { ok: !1, error: n instanceof Error ? n.message : String(n) };
} }
function He(e, r, t) { try {
    return ee(e, { correction: r, alphanumeric: !!t }).version;
}
catch (_a) {
    return -1;
} }

var QrGenCore = {
  registries: Qe,
  render: Pe,
  versionOf: He
};
