[colors]
[colors.primary]
background = "#dfe4c4"
foreground = "#1c2d28"

[colors.normal]
black   = "#dfe4c4"
red     = "#b14752"
green   = "#556753"
yellow  = "#dc8164"
blue    = "#4c6c94"
magenta = "#8a5b81"
cyan    = "#3d727d"
white   = "#384f54"

[colors.bright]
black   = "#7d8794"
red     = "#b14752"
green   = "#556753"
yellow  = "#dc8164"
blue    = "#4c6c94"
magenta = "#8a5b81"
cyan    = "#3d727d"
white   = "#1c2d28"

[colors.cursor]
text   = "#dfe4c4"
cursor = "#1c2d28"
