# Background and foreground colors
background = #dfe4c4
foreground = #1c2d28

# Standard colors
palette = 0=#dfe4c4
palette = 1=#b14752
palette = 2=#556753
palette = 3=#dc8164
palette = 4=#4c6c94
palette = 5=#8a5b81
palette = 6=#3d727d
palette = 7=#384f54

# Bright colors
palette = 8=#7d8794
palette = 9=#b14752
palette = 10=#556753
palette = 11=#dc8164
palette = 12=#4c6c94
palette = 13=#8a5b81
palette = 14=#3d727d
palette = 15=#1c2d28
