-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/harbor/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgba(253631ee)",
      inactive_border = "rgb(7d8794)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
    col = {
      border_active = "rgba(253631ee)",
      border_inactive = "rgb(7d8794)",
    },
    groupbar = {
      col = {
        active = "rgba(25363199)",
        inactive = "rgba(7d879488)",
      },
      text_color = "rgb(dc8164)",
      text_color_inactive = "rgba(1c2d28ee)",
    },
  },
  decoration = {
    rounding = 3,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(0, 0, 0, 0.3)",
    },
  },
})
